# Initially generated by GitHub Copilot.
"""Collect FOI data for Hebrew mark grammar exceptions and overrides."""

import unicodedata

import py_misc.my_unicode as my_unicode
from py_misc import uni_heb_char_classes as ucc
from pycmn import hebrew_points as hpo
from pycmn import str_defs as sd


_DUAL_CANTILLATION_LOCS = {
    ("Exodus", 20),
    ("Deuter", 5),
    ("Genesis", 35, 22),
}
_SLA_MARKS = frozenset((hpo.SHIND, hpo.SIND))
_DAGESH_MARKS = frozenset((hpo.DAGOMOSD,))
_VOWEL_MARKS = frozenset(ucc.VOWEL_POINTS)
_AOM_MARKS = frozenset(ucc.ACCENTS)
_FORMAT_CONTROLS = frozenset((sd.CGJ, sd.ZWJ))
_CLASS_ORDER = (
    "ordinary",
    "explicit-order",
    "initial-double-aom",
    "multi-vowel",
    "noninitial-double-aom",
    "unexpected-mark",
    "other-ordering",
)


def init():
    return {
        "summary-counts": {
            "total-clusters": 0,
            "excluded-atoms": 0,
            "ordinary": 0,
            "allowed-overrides": 0,
            "exotic": 0,
        },
        "class-counts": {class_key: 0 for class_key in _CLASS_ORDER},
        "sequence-counts-by-class": {class_key: {} for class_key in _CLASS_ORDER},
        "cases-by-class": {class_key: [] for class_key in _CLASS_ORDER[1:]},
    }


def collect_for_verse(fois, bcv, verse):
    if _is_excluded(*bcv):
        fois["summary-counts"]["excluded-atoms"] += len(verse)
        return
    for atidx, atom in enumerate(verse, start=1):
        assert isinstance(atom, list)
        assert len(atom) == 2
        atom_type, atom_text = atom
        bcvp = *bcv, atidx
        for cluster_idx, cluster in enumerate(_split_clusters(atom_text), start=1):
            _collect_for_cluster(fois, bcvp, atom_type, atom_text, cluster_idx, cluster)


def _is_excluded(bkid, chnu, vrnu):
    return (bkid, chnu) in _DUAL_CANTILLATION_LOCS or (
        bkid,
        chnu,
        vrnu,
    ) in _DUAL_CANTILLATION_LOCS


def _collect_for_cluster(fois, bcvp, atom_type, atom_text, cluster_idx, cluster):
    summary_counts = fois["summary-counts"]
    summary_counts["total-clusters"] += 1
    cluster_class, status_key = _classify(cluster, cluster_idx)
    summary_counts[status_key] += 1
    fois["class-counts"][cluster_class] += 1
    sequence = _mark_sequence(cluster)
    seq_counts = fois["sequence-counts-by-class"][cluster_class]
    seq_counts[sequence] = seq_counts.get(sequence, 0) + 1
    if cluster_class == "ordinary":
        return
    fois["cases-by-class"][cluster_class].append(
        {
            "bcvp": _bcvp_str(bcvp),
            "atom-type": atom_type,
            "atom": atom_text,
            "cluster-index": cluster_idx,
            "cluster": cluster["letter"] + "".join(cluster["marks"]),
            "sequence": sequence,
            "mark-names": ", ".join(my_unicode.name(mark) for mark in cluster["marks"]),
        }
    )


def _split_clusters(atom_text):
    clusters = []
    current = None
    for ch in atom_text:
        if ch in ucc.LETTERS:
            current = {"letter": ch, "marks": []}
            clusters.append(current)
            continue
        if current is None:
            continue
        if unicodedata.category(ch) in ("Mn", "Cf"):
            current["marks"].append(ch)
    return clusters


def _classify(cluster, cluster_idx):
    marks = cluster["marks"]
    if _unexpected_marks(marks):
        return "unexpected-mark", "exotic"
    if _is_ordinary(marks):
        return "ordinary", "ordinary"
    if any(mark in _FORMAT_CONTROLS for mark in marks):
        return "explicit-order", "allowed-overrides"
    if cluster_idx == 1 and _is_initial_double_aom(marks):
        return "initial-double-aom", "allowed-overrides"
    if _mark_sequence(marks).count("v") > 1:
        return "multi-vowel", "exotic"
    if _mark_sequence(marks).count("a") > 1:
        return "noninitial-double-aom", "exotic"
    return "other-ordering", "exotic"


def _is_ordinary(marks):
    if any(mark in _FORMAT_CONTROLS for mark in marks):
        return False
    sequence = _mark_sequence(marks)
    if not _is_in_nondecreasing_order(sequence):
        return False
    return all(sequence.count(mark_class) <= 1 for mark_class in "sdva")


def _is_initial_double_aom(marks):
    sequence = _mark_sequence(marks)
    if not sequence.endswith("aa"):
        return False
    prefix = sequence[:-2]
    return _is_in_nondecreasing_order(prefix) and all(
        prefix.count(mark_class) <= 1 for mark_class in "sdv"
    )


def _is_in_nondecreasing_order(sequence):
    sort_order = {"s": 0, "d": 1, "v": 2, "a": 3}
    last = -1
    for mark_class in sequence:
        current = sort_order[mark_class]
        if current < last:
            return False
        last = current
    return True


def _unexpected_marks(marks):
    return [mark for mark in marks if _mark_class(mark) == "?"]


def _mark_sequence(cluster_or_marks):
    marks = (
        cluster_or_marks["marks"]
        if isinstance(cluster_or_marks, dict)
        else cluster_or_marks
    )
    return "".join(_mark_class(mark) for mark in marks if _mark_class(mark) != "f")


def _mark_class(mark):
    if mark in _SLA_MARKS:
        return "s"
    if mark in _DAGESH_MARKS:
        return "d"
    if mark in _VOWEL_MARKS:
        return "v"
    if mark in _AOM_MARKS:
        return "a"
    if mark in _FORMAT_CONTROLS:
        return "f"
    return "?"


def _bcvp_str(bcvp):
    bkid, chnu, vrnu, atnu = bcvp
    return f"{bkid} {chnu}:{vrnu}.{atnu}"
