# Initially generated by GitHub Copilot.
"""Update vendored files from the MAM-basics sibling repository.

UXLC-utils vendors a curated subset of MAM-basics's ``py/mb_cmn`` and
``py/mb_diff_mpu`` (the slice that ``clc.clc_dual_cant`` needs to name accents
canonically via ``mb_diff_mpu.describe_diff``). The vendored set is defined by
what is already present in each destination directory: ``copy_by_intersection``
refreshes exactly those files from the sibling, so adding a file to the subset
means dropping it in the destination once, then re-running this.

Unlike wlc-utils's equivalent driver this has no ``repo_paths``/``cmn``
dependency: MAM-basics is located as a GitRepos sibling and UTF-8 stdio is set
up directly. ``mb_cmn/mb_cmn_bib_locales.py`` is UXLC-local (MAM-basics names it
``bib_locales.py``), so it is excluded from the strict intersection — it stays
local and untouched.
"""

import argparse
import datetime
import hashlib
import sys
from pathlib import Path

from mb_cmn import vendoring_sync

_REPO = Path(__file__).resolve().parents[1]  # UXLC-utils/
_GITREPOS = _REPO.parent  # GitRepos/
_SOURCE_REPO = _GITREPOS / "MAM-basics"

_SOURCE_PYCMN = _SOURCE_REPO / "py" / "mb_cmn"
_DEST_PYCMN = _REPO / "py" / "mb_cmn"
_SOURCE_MBDIFF = _SOURCE_REPO / "py" / "mb_diff_mpu"
_DEST_MBDIFF = _REPO / "py" / "mb_diff_mpu"

# UXLC-local file whose MAM-basics counterpart has a different name; never synced.
_PYCMN_EXCLUDE = ("mb_cmn_bib_locales.py",)


def main() -> None:
    args = _parse_args()
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    for path in (
        _SOURCE_REPO,
        _SOURCE_PYCMN,
        _DEST_PYCMN,
        _SOURCE_MBDIFF,
        _DEST_MBDIFF,
    ):
        _require_dir(path)

    synced_pycmn, changed_pycmn = _sync(
        _SOURCE_PYCMN, _DEST_PYCMN, exclude_rel_paths=_PYCMN_EXCLUDE
    )
    synced_mbdiff, changed_mbdiff = _sync(_SOURCE_MBDIFF, _DEST_MBDIFF)

    commit, tag = vendoring_sync.get_git_info(_SOURCE_REPO)
    date_str = datetime.date.today().isoformat()
    wrote_pycmn = _maybe_write_provenance(
        _DEST_PYCMN,
        source_rel="MAM-basics/py/mb_cmn",
        copied_files=synced_pycmn,
        commit=commit,
        tag=tag,
        date_str=date_str,
        changed=changed_pycmn,
        force=args.force_provenance,
    )
    wrote_mbdiff = _maybe_write_provenance(
        _DEST_MBDIFF,
        source_rel="MAM-basics/py/mb_diff_mpu",
        copied_files=synced_mbdiff,
        commit=commit,
        tag=tag,
        date_str=date_str,
        changed=changed_mbdiff,
        force=args.force_provenance,
    )

    _report(_DEST_PYCMN, synced_pycmn, changed_pycmn, wrote_pycmn)
    _report(_DEST_MBDIFF, synced_mbdiff, changed_mbdiff, wrote_mbdiff)
    print(f"MAM-basics commit: {commit}")
    if tag:
        print(f"MAM-basics tag:    {tag}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force-provenance",
        action="store_true",
        help=(
            "Rewrite each _provenance.md even when no vendored file content "
            "changed. By default _provenance.md is left untouched (no date/commit "
            "bump) when the sync copied no new content."
        ),
    )
    return parser.parse_args()


def _sync(src_dir: Path, dest_dir: Path, exclude_rel_paths=()):
    """Copy src_dir into dest_dir, returning (copied_files, content_changed)."""
    before = _content_digest(dest_dir)
    copied = vendoring_sync.copy_by_intersection(
        src_dir,
        dest_dir,
        include_suffixes=(".py",),
        strict=True,
        exclude_rel_paths=exclude_rel_paths,
    )
    changed = _content_digest(dest_dir) != before
    return copied, changed


def _content_digest(dest_dir: Path) -> dict:
    """Map each .py dest filename to a hash of its bytes (non-recursive)."""
    digest = {}
    for path in dest_dir.iterdir():
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        if path.suffix != ".py":
            continue
        digest[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest


def _maybe_write_provenance(
    dest_dir: Path,
    *,
    source_rel: str,
    copied_files,
    commit: str,
    tag,
    date_str: str,
    changed: bool,
    force: bool,
) -> bool:
    """Write _provenance.md only when content changed (or force). Return whether written."""
    if not (changed or force):
        return False
    vendoring_sync.write_provenance(
        dest_dir,
        source_rel=source_rel,
        copied_files=copied_files,
        commit=commit,
        tag=tag,
        date_str=date_str,
    )
    return True


def _report(dest_dir: Path, copied, changed: bool, wrote: bool) -> None:
    if wrote:
        provenance = "provenance updated" if changed else "provenance forced"
    else:
        provenance = "unchanged, provenance kept"
    print(f"{dest_dir.relative_to(_REPO)}: copied {len(copied)} files ({provenance})")


def _require_dir(path: Path) -> None:
    if not path.is_dir():
        raise FileNotFoundError(f"Directory does not exist: {path}")


if __name__ == "__main__":
    main()
