# Initially generated by GitHub Copilot.
"""Run downstream rebuilds after refreshing UXLC inputs."""

import main_fois
import main_write_page_break_info


_STEPS = [
    main_fois,
    main_write_page_break_info,
]


def main():
    """Run derived-output rebuilds that depend on refreshed UXLC XML."""
    for mod in _STEPS:
        print(f"{__name__} {mod.__name__}")
        mod.main()


if __name__ == "__main__":
    main()
