# Initially generated by GitHub Copilot.
"""Run routine downstream rebuilds after refreshing UXLC inputs."""

import main_amb_early_mtg
import main_fois
import main_uxlc_check_changes
import main_uxlc_word_list
import main_write_page_break_info


_STEPS = [
    main_uxlc_check_changes,
    main_fois,
    main_write_page_break_info,
    main_amb_early_mtg,
    main_uxlc_word_list,
]


def main():
    """Run derived-output rebuilds that depend on refreshed UXLC inputs."""
    for mod in _STEPS:
        print(f"{__name__} {mod.__name__}")
        mod.main()


if __name__ == "__main__":
    main()
