# Initially generated by GitHub Copilot.
"""Helpers for stable generation provenance breadcrumbs."""

from pathlib import Path

_SIDECAR_NAME = "provenance.md"


def generated_by_text(generator_file: str) -> str:
    """Return a stable human-readable generated-by string."""
    return f"This file was generated by {_display_path(generator_file)}."


def generated_html_comment(generator_file: str) -> str:
    """Return an HTML comment payload for a generated file."""
    return f"Do not edit by hand. {generated_by_text(generator_file)}"


def with_json_provenance(root, generator_file: str):
    """Return a JSON root dict with provenance inserted as the first key."""
    if not isinstance(root, dict):
        raise TypeError("JSON provenance injection requires a top-level dict")
    rest = {key: value for key, value in root.items() if key != "provenance"}
    return {"provenance": generated_by_text(generator_file), **rest}


def write_directory_provenance(
    dir_path: str, generator_file: str, artifacts_description: str
):
    """Write a provenance sidecar for a directory of generated artifacts."""
    out_path = Path(dir_path) / _SIDECAR_NAME
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out_fp:
        out_fp.write(
            directory_provenance_markdown(generator_file, artifacts_description)
        )


def directory_provenance_markdown(
    generator_file: str, artifacts_description: str
) -> str:
    """Return Markdown text for a directory-level provenance sidecar."""
    description = artifacts_description.rstrip(".")
    return "\n".join(
        (
            "<!-- Initially generated by GitHub Copilot. -->",
            "# Provenance",
            "",
            f"This directory contains generated {description}.",
            generated_by_text(generator_file),
            "Payload files in this directory remain in their native data format, so provenance is recorded here rather than inside each file.",
            "",
        )
    )


def _display_path(generator_file: str) -> str:
    generator_path = Path(generator_file).resolve()
    repo_root = Path(__file__).resolve().parents[2]
    repos_root = repo_root.parent
    for base_path in (repo_root, repos_root):
        try:
            return generator_path.relative_to(base_path).as_posix()
        except ValueError:
            continue
    return generator_path.as_posix()
