# Initially generated by GitHub Copilot.
"""Polite HTTP downloading utilities."""

from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
import random
import time
from urllib.parse import urlsplit, urlunsplit
from urllib.robotparser import RobotFileParser

import requests


_RETRYABLE_STATUS_CODES = (408, 429, 500, 502, 503, 504)


class RobotsDisallowedError(RuntimeError):
    """Raised when robots.txt disallows a request."""


@dataclass(frozen=True)
class RetryConfig:
    """Retry behavior for transient HTTP failures."""

    max_attempts: int = 4
    first_backoff_s: float = 1.0
    max_backoff_s: float = 30.0
    retryable_status_codes: tuple[int, ...] = _RETRYABLE_STATUS_CODES


@dataclass(frozen=True)
class ThrottleConfig:
    """Per-host throttling between request starts."""

    min_delay_s: float = 0.0
    mean_delay_s: float = 0.0

    def give_delay_s(self, expovariate_fun):
        """Return the next inter-request delay."""
        min_delay_s = max(self.min_delay_s, 0.0)
        mean_delay_s = max(self.mean_delay_s, 0.0)
        if mean_delay_s <= min_delay_s:
            return min_delay_s
        extra = expovariate_fun(1.0 / (mean_delay_s - min_delay_s))
        return min_delay_s + extra


@dataclass(frozen=True)
class CacheConfig:
    """On-disk cache for conditional GETs."""

    dir_path: str | None = None


@dataclass(frozen=True)
class PoliteDownloadConfig:
    """Configuration for polite HTTP downloads."""

    user_agent: str
    default_timeout_s: float = 30.0
    accept_language: str | None = None
    referer: str | None = None
    default_headers: dict[str, str] = field(default_factory=dict)
    throttle: ThrottleConfig = field(default_factory=ThrottleConfig)
    retry: RetryConfig = field(default_factory=RetryConfig)
    cache: CacheConfig = field(default_factory=CacheConfig)
    obey_robots_txt: bool = False

    def give_base_headers(self):
        """Return the default headers for the downloader session."""
        headers = {"User-Agent": self.user_agent}
        if self.accept_language is not None:
            headers["Accept-Language"] = self.accept_language
        if self.referer is not None:
            headers["Referer"] = self.referer
        headers.update(self.default_headers)
        return headers


@dataclass(frozen=True)
class DownloadResult:
    """Binary download result with encoding metadata."""

    body: bytes
    encoding: str | None
    final_url: str


@dataclass(frozen=True)
class _CacheEntry:
    body: bytes
    encoding: str | None
    etag: str | None
    last_modified: str | None
    final_url: str


class PoliteDownloader:
    """HTTP client with throttling, retries, caching, and robots checks."""

    def __init__(
        self,
        config: PoliteDownloadConfig,
        session: requests.Session | None = None,
        sleep_fun=time.sleep,
        monotonic_fun=time.monotonic,
        expovariate_fun=random.expovariate,
    ):
        self._config = config
        self._session = session if session is not None else requests.Session()
        self._session.headers.update(config.give_base_headers())
        self._sleep_fun = sleep_fun
        self._monotonic_fun = monotonic_fun
        self._expovariate_fun = expovariate_fun
        self._last_request_start_by_host = {}
        self._robots_by_origin = {}

    def close(self):
        """Close the underlying HTTP session."""
        self._session.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.close()
        return False

    def get_bytes(
        self,
        url,
        *,
        params=None,
        headers=None,
        timeout=None,
        allow_cache=True,
        obey_robots=None,
    ):
        """GET bytes from a URL."""
        return self._request(
            "GET",
            url,
            params=params,
            headers=headers,
            timeout=timeout,
            allow_cache=allow_cache,
            obey_robots=obey_robots,
        ).body

    def get_text(
        self,
        url,
        *,
        params=None,
        headers=None,
        timeout=None,
        allow_cache=True,
        obey_robots=None,
        encoding=None,
    ):
        """GET text from a URL."""
        result = self._request(
            "GET",
            url,
            params=params,
            headers=headers,
            timeout=timeout,
            allow_cache=allow_cache,
            obey_robots=obey_robots,
        )
        encoding = encoding or result.encoding or "utf-8"
        return result.body.decode(encoding)

    def get_json(
        self,
        url,
        *,
        params=None,
        headers=None,
        timeout=None,
        allow_cache=True,
        obey_robots=None,
        encoding=None,
    ):
        """GET JSON from a URL."""
        text = self.get_text(
            url,
            params=params,
            headers=headers,
            timeout=timeout,
            allow_cache=allow_cache,
            obey_robots=obey_robots,
            encoding=encoding,
        )
        return json.loads(text)

    def _request(
        self,
        method,
        url,
        *,
        params=None,
        headers=None,
        timeout=None,
        allow_cache=True,
        obey_robots=None,
    ):
        method = method.upper()
        timeout = self._config.default_timeout_s if timeout is None else timeout
        obey_robots = (
            self._config.obey_robots_txt if obey_robots is None else obey_robots
        )
        cache_entry = None
        prepared_url = self._prepare_url(method, url, params)
        if method == "GET" and allow_cache:
            cache_entry = self._read_cache_entry(prepared_url)
        if method == "GET" and obey_robots:
            self._assert_allowed_by_robots(prepared_url)
        attempts = max(self._config.retry.max_attempts, 1)
        for attempt in range(1, attempts + 1):
            request_headers = dict(headers or {})
            if cache_entry is not None:
                if cache_entry.etag is not None:
                    request_headers["If-None-Match"] = cache_entry.etag
                if cache_entry.last_modified is not None:
                    request_headers["If-Modified-Since"] = cache_entry.last_modified
            self._throttle(prepared_url)
            try:
                response = self._session.request(
                    method,
                    url,
                    params=params,
                    headers=request_headers or None,
                    timeout=timeout,
                )
            except (requests.ConnectionError, requests.Timeout):
                if attempt == attempts:
                    raise
                self._sleep_retry_backoff(attempt)
                continue
            if response.status_code == 304:
                if cache_entry is None:
                    raise RuntimeError(
                        f"Received 304 without cached content for {prepared_url}"
                    )
                return DownloadResult(
                    cache_entry.body,
                    cache_entry.encoding,
                    cache_entry.final_url,
                )
            if response.status_code in self._config.retry.retryable_status_codes:
                if attempt == attempts:
                    response.raise_for_status()
                self._sleep_retry_backoff(attempt)
                continue
            response.raise_for_status()
            result = DownloadResult(
                response.content,
                response.encoding or response.apparent_encoding,
                response.url,
            )
            if method == "GET" and allow_cache:
                self._write_cache_entry(prepared_url, result, response.headers)
            return result
        raise RuntimeError(f"Retry loop exhausted for {prepared_url}")

    def _throttle(self, url):
        throttle = self._config.throttle
        delay_s = throttle.give_delay_s(self._expovariate_fun)
        if delay_s <= 0.0:
            return
        host = urlsplit(url).netloc
        now = self._monotonic_fun()
        previous_start = self._last_request_start_by_host.get(host)
        sleep_s = 0.0
        if previous_start is not None:
            elapsed_s = now - previous_start
            sleep_s = max(delay_s - elapsed_s, 0.0)
        if sleep_s > 0.0:
            self._sleep_fun(sleep_s)
        self._last_request_start_by_host[host] = now + sleep_s

    def _sleep_retry_backoff(self, attempt):
        retry = self._config.retry
        backoff_s = retry.first_backoff_s * (2 ** (attempt - 1))
        self._sleep_fun(min(backoff_s, retry.max_backoff_s))

    def _assert_allowed_by_robots(self, url):
        parsed = urlsplit(url)
        origin = (parsed.scheme, parsed.netloc)
        parser = self._robots_by_origin.get(origin)
        if parser is None:
            parser = self._read_robots_parser(parsed.scheme, parsed.netloc)
            self._robots_by_origin[origin] = parser
        if not parser.can_fetch(self._config.user_agent, url):
            raise RobotsDisallowedError(f"robots.txt disallows {url}")

    def _read_robots_parser(self, scheme, netloc):
        robots_url = urlunsplit((scheme, netloc, "/robots.txt", "", ""))
        self._throttle(robots_url)
        response = self._session.request(
            "GET",
            robots_url,
            timeout=self._config.default_timeout_s,
        )
        parser = RobotFileParser()
        parser.set_url(robots_url)
        if response.status_code == 404:
            parser.parse([])
            return parser
        response.raise_for_status()
        parser.parse(response.text.splitlines())
        return parser

    def _read_cache_entry(self, prepared_url):
        paths = self._cache_paths(prepared_url)
        if paths is None:
            return None
        meta_path, body_path = paths
        if not meta_path.exists() or not body_path.exists():
            return None
        with open(meta_path, encoding="utf-8") as meta_fp:
            meta = json.load(meta_fp)
        with open(body_path, "rb") as body_fp:
            body = body_fp.read()
        return _CacheEntry(
            body=body,
            encoding=meta.get("encoding"),
            etag=meta.get("etag"),
            last_modified=meta.get("last_modified"),
            final_url=meta["final_url"],
        )

    def _write_cache_entry(self, prepared_url, result, response_headers):
        paths = self._cache_paths(prepared_url)
        if paths is None:
            return
        meta_path, body_path = paths
        meta_path.parent.mkdir(parents=True, exist_ok=True)
        meta = {
            "encoding": result.encoding,
            "etag": response_headers.get("ETag"),
            "final_url": result.final_url,
            "last_modified": response_headers.get("Last-Modified"),
        }
        with open(meta_path, "w", encoding="utf-8") as meta_fp:
            json.dump(meta, meta_fp, ensure_ascii=False, indent=2)
            meta_fp.write("\n")
        with open(body_path, "wb") as body_fp:
            body_fp.write(result.body)

    def _cache_paths(self, prepared_url):
        dir_path = self._config.cache.dir_path
        if dir_path is None:
            return None
        cache_dir = Path(dir_path)
        digest = hashlib.sha256(prepared_url.encode("utf-8")).hexdigest()
        return cache_dir / f"{digest}.json", cache_dir / f"{digest}.body"

    @staticmethod
    def _prepare_url(method, url, params):
        return requests.Request(method=method, url=url, params=params).prepare().url
