# Initially generated by GitHub Copilot.
"""Exports write, summary."""

import json
from pathlib import PurePosixPath
import re

import py_misc.my_html as my_html
import py_fois.fois_mark_name_abbrev as fois_mark_name_abbrev
import py_fois.fois_mark_grammar_foi as fois_mark_grammar_foi


_MARK_CLASS_ORDER = (
    "ordinary",
    "explicit-order",
    "initial-double-aom",
    "multi-vowel",
    "noninitial-double-aom",
    "unexpected-mark",
    "other-ordering",
)
_MARK_CASE_HEADERS = (
    "bcvp",
    "notes",
    "change",
    "atom",
    "sequence",
    "mark names",
)
_MARK_CASE_HEADER_LABELS = {
    "bcvp": "bcvp",
    "notes": "n",
    "atom": "atom",
    "change": "c",
    "sequence": "seq",
    "mark names": "mark names",
}
_MARK_CASE_HEADER_TOOLTIPS = {
    "change": "most recent change record",
    "notes": "notes",
    "sequence": "sequence",
}
_GRAMMAR_ORDER_ROWS = (
    ("shsi-dot", "shin-dot or sin-dot"),
    ("dms", "dagesh/mapiq/shuruq-dot"),
    ("vowel", ""),
    ("aom", "accent or meteg"),
)
_ABBREVIATION_ROWS = (
    ("metuq", "meteg/siluq"),
    ("CGJ", "combining grapheme joiner"),
    ("ZWJ", "zero-width joiner"),
)
_ABBREVIATION_TOOLTIP_TITLES = {
    "shsi-dot": "shin-dot or sin-dot",
    "dms": "dagesh/mapiq/shuruq-dot",
    "ba-is": "below-accents including silluq",
    "metuq": "meteg/siluq",
    "CGJ": "combining grapheme joiner",
    "ZWJ": "zero-width joiner",
    "xataf": "one of the three ḥataf vowels",
    "pq-vowel": "pataḥ or qamats",
    "xs-vowel": "ḥiriq or sheva",
    "pre-wm": "prepositive that can occur with meteg: telisha gedolah, deḥi, geresh muqdam",
}
_ABBREVIATION_TOOLTIP_PATTERN = re.compile(
    "|".join(
        re.escape(abbreviation)
        for abbreviation in sorted(_ABBREVIATION_TOOLTIP_TITLES, key=len, reverse=True)
    )
)
_BCVP_PATTERN = re.compile(
    r"^(?P<book>.+) (?P<chapter>\d+):(?P<verse>\d+)\.(?P<atom>\d+)$"
)
_ALL_CHANGES_PATH = "out/UXLC-misc/all_changes.json"
_TANACH_US_BOOK_CODES = {
    "Genesis": "Gen",
    "Exodus": "Ex",
    "Levit": "Lev",
    "Numbers": "Num",
    "Deuter": "Deut",
    "Joshua": "Josh",
    "Judges": "Judg",
    "1Samuel": "1Sam",
    "2Samuel": "2Sam",
    "1Kings": "1Kings",
    "2Kings": "2Kings",
    "Isaiah": "Isa",
    "Jeremiah": "Jer",
    "Ezekiel": "Ezek",
    "Hosea": "Hos",
    "Joel": "Joel",
    "Amos": "Am",
    "Obadiah": "Ob",
    "Jonah": "Jon",
    "Micah": "Mic",
    "Nahum": "Nah",
    "Habakkuk": "Hab",
    "Tsefaniah": "Zeph",
    "Haggai": "Hag",
    "Zechariah": "Zech",
    "Malachi": "Mal",
    "Psalms": "Ps",
    "Proverbs": "Prov",
    "Job": "Job",
    "Song of Songs": "Song",
    "Ruth": "Ruth",
    "Lamentations": "Lam",
    "Ecclesiastes": "Eccl",
    "Esther": "Esth",
    "Daniel": "Dan",
    "Ezra": "Ezra",
    "Nehemiah": "Neh",
    "1Chronicles": "1Chr",
    "2Chronicles": "2Chr",
}


def _count_str(value):
    return f"{value:,}"


def summary(mark_catalog):
    summary_counts = mark_catalog["summary-counts"]
    return (
        f"{_count_str(summary_counts['total-clusters'])} clusters; "
        f"{_count_str(summary_counts['ordinary'])} ordinary; "
        f"{_count_str(summary_counts['treated-as-ordinary'])} treated as ordinary; "
        f"{_count_str(summary_counts['weird'])} weird listed below"
    )


def write(mark_catalog, json_output_path, out_path):
    summary_counts = mark_catalog["summary-counts"]
    visible_class_keys = _visible_class_keys(mark_catalog)
    latest_change_by_atom = _latest_change_by_atom()
    page_exclusions = fois_mark_grammar_foi.page_exclusions()
    body_items = [
        my_html.heading_level_1("mark-grammar (UXLC features of interest)"),
        my_html.para(
            [
                my_html.anchor("FOI index", {"href": "index.html"}),
                " | ",
                *_json_link_contents(json_output_path),
            ]
        ),
        my_html.para(
            "This page lists the weird Hebrew letter clusters: those that are neither ordinary nor treated as ordinary."
        ),
        _grammar_order_table(),
        my_html.heading_level_2("Abbreviations"),
        _abbreviation_table(),
        my_html.para("Exclusions:"),
        my_html.unordered_list(page_exclusions),
        my_html.para(
            [
                "Clusters treated as ordinary are listed in ",
                my_html.anchor("mark grammar 2", {"href": "foi-mark-grammar-2.html"}),
                ".",
            ]
        ),
        my_html.para(_weird_summary_text(summary_counts, visible_class_keys)),
    ]
    if visible_class_keys:
        body_items.extend(
            [
                my_html.heading_level_2("Counts by weird class"),
                _class_counts_table(mark_catalog, visible_class_keys),
                *_sections(mark_catalog, visible_class_keys, latest_change_by_atom),
            ]
        )
    body_contents = _body_wrapper(body_items)
    _write_html("mark-grammar (UXLC features of interest)", out_path, body_contents)


def _ordinary_pattern_display_list(display_items):
    return my_html.unordered_list(
        tuple(
            _ordinary_pattern_display_list_item(display_item)
            for display_item in display_items
        )
    )


def _ordinary_pattern_display_list_item(display_item):
    text = _tooltipify_abbreviations(display_item.text)
    if not display_item.subitems:
        return text
    if isinstance(text, str):
        return (text, _ordinary_pattern_display_list(display_item.subitems))
    return (*text, _ordinary_pattern_display_list(display_item.subitems))


def _visible_class_keys(mark_catalog):
    return tuple(
        class_key
        for class_key in _MARK_CLASS_ORDER[1:]
        if mark_catalog["class-counts"][class_key] > 0
    )


def _weird_summary_text(summary_counts, visible_class_keys):
    summary_text = (
        f"There are {_count_str(summary_counts['total-clusters'])} included "
        f"clusters; {_count_str(summary_counts['ordinary'])} are ordinary, "
        f"{_count_str(summary_counts['treated-as-ordinary'])} are treated as ordinary, "
        f"and {_count_str(summary_counts['weird'])} are weird"
    )
    if visible_class_keys:
        return f"{summary_text} listed below."
    return f"{summary_text}."


def _class_counts_table(mark_catalog, visible_class_keys):
    rows = [my_html.table_row_of_headers(("class", "count", "details"))]
    for class_key in visible_class_keys:
        rows.append(_class_count_row(class_key, mark_catalog))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _class_count_row(class_key, mark_catalog):
    count = mark_catalog["class-counts"][class_key]
    detail_contents = my_html.anchor(
        f"{_count_str(len(mark_catalog['cases-by-class'][class_key]))} cases",
        {"href": f"#{_section_id(class_key)}"},
    )
    return my_html.table_row_of_data(
        (
            _class_label(class_key),
            _count_str(count),
            detail_contents,
        )
    )


def _sections(mark_catalog, visible_class_keys, latest_change_by_atom):
    sections = []
    for class_key in visible_class_keys:
        sections.extend(_section(class_key, mark_catalog, latest_change_by_atom))
    return sections


def _section(class_key, mark_catalog, latest_change_by_atom):
    cases = mark_catalog["cases-by-class"][class_key]
    heading = my_html.heading_level_2(
        f"{_class_label(class_key)} ({_count_str(len(cases))} cases)",
        {"id": _section_id(class_key)},
    )
    return [
        heading,
        _cases_table(cases, latest_change_by_atom),
    ]


def _abbreviation_table():
    rows = [my_html.table_row_of_headers(("abbreviation", "meaning"))]
    rows.extend(my_html.table_row_of_data(row) for row in _ABBREVIATION_ROWS)
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _grammar_order_table():
    rows = [my_html.table_row_of_headers(("item", "meaning"))]
    rows.extend(
        my_html.table_row(
            (
                my_html.table_datum(item),
                my_html.table_datum(_tooltipify_abbreviations(meaning)),
            )
        )
        for item, meaning in _GRAMMAR_ORDER_ROWS
    )
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _cases_table(cases, latest_change_by_atom):
    rows = [
        my_html.table_row_of_headers(
            tuple(
                _mark_case_header_label(field_name) for field_name in _MARK_CASE_HEADERS
            )
        )
    ]
    rows.extend(_case_row(case_dic, latest_change_by_atom) for case_dic in cases)
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _mark_case_header_label(field_name):
    label = _MARK_CASE_HEADER_LABELS[field_name]
    if field_name not in _MARK_CASE_HEADER_TOOLTIPS:
        return label
    return my_html.span(
        label,
        {
            "class": "abbrev-tooltip",
            "title": _MARK_CASE_HEADER_TOOLTIPS[field_name],
        },
    )


def _highlighted_atom(case_dic):
    return _highlighted_atom_contents(case_dic["atom"], case_dic["cluster-index"])


def _highlighted_atom_contents(atom_text, target_cluster):
    cluster_ranges = fois_mark_grammar_foi.atom_cluster_ranges(atom_text)
    row_contents = []
    cursor = 0
    for cluster_idx, (start, end) in enumerate(cluster_ranges, start=1):
        if cursor < start:
            row_contents.append(atom_text[cursor:start])
        cluster_text = atom_text[start:end]
        if cluster_idx == target_cluster:
            row_contents.append(
                my_html.span(cluster_text, {"class": "cluster-highlight"})
            )
        else:
            row_contents.append(cluster_text)
        cursor = end
    if cursor < len(atom_text):
        row_contents.append(atom_text[cursor:])
    return tuple(row_contents)


def _as_contents(value):
    if isinstance(value, tuple):
        return value
    return (value,)


def _styled_comment_atom(comment):
    return my_html.span(
        _highlighted_atom_contents(comment["atom"], comment["cluster-index"]),
        {"lang": "hbo", "dir": "rtl"},
    )


def _mark_names_cell_contents(case_dic):
    contents = list(_as_contents(_abbreviate_mark_names(case_dic["mark names"])))
    comment = case_dic.get("mark names comment")
    if comment is None:
        return tuple(contents)
    contents.append(my_html.line_break())
    contents.append(comment["prefix"])
    contents.append(_styled_comment_atom(comment))
    return tuple(contents)


def _case_row(case_dic, latest_change_by_atom):
    row_cells = []
    for field_name in _MARK_CASE_HEADERS:
        if field_name == "bcvp":
            row_cells.append(my_html.table_datum(_linked_bcvp(case_dic[field_name])))
            continue
        if field_name == "atom":
            row_cells.append(
                my_html.table_datum(
                    _highlighted_atom(case_dic), {"lang": "hbo", "dir": "rtl"}
                )
            )
            continue
        if field_name == "change":
            row_cells.append(
                my_html.table_datum(
                    _change_record_link(case_dic, latest_change_by_atom)
                )
            )
            continue
        if field_name == "sequence":
            row_cells.append(my_html.table_datum(_sequence_label(case_dic[field_name])))
            continue
        if field_name == "mark names":
            row_cells.append(my_html.table_datum(_mark_names_cell_contents(case_dic)))
            continue
        row_cells.append(my_html.table_datum(case_dic[field_name]))
    return my_html.table_row(tuple(row_cells))


def _change_record_link(case_dic, latest_change_by_atom):
    release_and_id = latest_change_by_atom.get(case_dic["atom"])
    if release_and_id is None:
        return ""
    return my_html.anchor("•", {"href": _uxlc_change_url(release_and_id)})


def _latest_change_by_atom():
    with open(_ALL_CHANGES_PATH, encoding="utf-8") as changes_fp:
        changes = json.load(changes_fp)
    latest_change_by_atom = {}
    for change in changes:
        release_and_id = (change["release"], f"{change['changeset']}-{change['n']}")
        sort_key = (change["release"], change["changeset"], int(change["n"]))
        for field_name in ("reftext", "changetext"):
            atom = change.get(field_name)
            if not atom:
                continue
            previous = latest_change_by_atom.get(atom)
            if previous is None or sort_key > previous[0]:
                latest_change_by_atom[atom] = (sort_key, release_and_id)
    return {
        atom: release_and_id
        for atom, (_sort_key, release_and_id) in latest_change_by_atom.items()
    }


def _uxlc_change_url(release_and_id):
    release_date, change_id = release_and_id
    release_str = f"{release_date}%20-%20Changes"
    return f"https://hcanat.us/Changes/{release_str}/{release_str}.xml?{change_id}"


def _abbreviate_mark_names(mark_names):
    return _tooltipify_abbreviations(
        fois_mark_name_abbrev.abbreviate_mark_names(mark_names)
    )


def _tooltipify_abbreviations(text):
    parts = []
    last_end = 0
    for match in _ABBREVIATION_TOOLTIP_PATTERN.finditer(text):
        if last_end < match.start():
            parts.append(text[last_end : match.start()])
        abbreviation = match.group(0)
        parts.append(
            my_html.span(
                abbreviation,
                {
                    "class": "abbrev-tooltip",
                    "title": _ABBREVIATION_TOOLTIP_TITLES[abbreviation],
                },
            )
        )
        last_end = match.end()
    if not parts:
        return text
    if last_end < len(text):
        parts.append(text[last_end:])
    return tuple(parts)


def _linked_bcvp(bcvp_str):
    match = _BCVP_PATTERN.fullmatch(bcvp_str)
    if match is None:
        return bcvp_str
    book = match.group("book")
    chapter = match.group("chapter")
    verse = match.group("verse")
    atom = match.group("atom")
    bcv_str = f"{_tanach_us_book_code(book)} {chapter}:{verse}"
    return (
        my_html.anchor(
            bcv_str,
            {"href": _tanach_us_bcv_url(book, chapter, verse)},
        ),
        f".{atom}",
    )


def _tanach_us_book_code(book):
    return _TANACH_US_BOOK_CODES[book]


def _tanach_us_bcv_url(book, chapter, verse):
    return f"https://tanach.us/Tanach.xml?{_tanach_us_book_code(book)}{chapter}:{verse}"


def _class_label(class_key):
    return {
        "ordinary": "ordinary",
        "explicit-order": "explicit-order",
        "initial-double-aom": "initial-double-aom",
        "multi-vowel": "multi-vowel",
        "noninitial-double-aom": "noninitial-double-aom",
        "unexpected-mark": "unexpected-mark",
        "other-ordering": "other-ordering",
    }[class_key]


def _sequence_label(sequence):
    return sequence or "(bare-letter)"


def _section_id(class_key):
    return f"intro-{class_key}"


def _json_link_contents(json_output_path):
    return [
        "JSON catalog: ",
        my_html.anchor(
            _json_basename(json_output_path),
            {"href": _json_basename(json_output_path)},
        ),
    ]


def _json_basename(json_output_path):
    return PurePosixPath(json_output_path).name


def _body_wrapper(contents):
    style = "max-width: 50rem; margin-left: auto; margin-right: auto"
    return [my_html.div(contents, {"style": style})]


def _write_html(title, out_path, body_contents):
    write_ctx = my_html.WriteCtx(title, out_path)
    my_html.write_html_to_file(body_contents, write_ctx, "../")
