# Initially generated by GitHub Copilot.
"""Collect FOI data for Hebrew mark grammar exceptions and overrides."""

from collections.abc import Callable
from dataclasses import dataclass
import unicodedata

import py_misc.my_unicode as my_unicode
import py_fois.uni_heb_char_classes as ucc
from pycmn import hebrew_letters as hl
from pycmn import hebrew_accents as ha
from pycmn import hebrew_points as hpo
from pycmn import hebrew_punctuation as hpu
from pycmn import str_defs as sd


_DUAL_CANTILLATION_LOCS = {
    ("Exodus", 20),
    ("Deuter", 5),
    ("Genesis", 35, 22),
}
_SHSI_DOT_MARKS = frozenset((hpo.SHIND, hpo.SIND))
_DAGESH_MARKS = frozenset((hpo.DAGOMOSD, hpo.RAFE))
_VOWEL_MARKS = frozenset(ucc.VOWEL_POINTS)
_AOM_MARKS = frozenset(ucc.ACCENTS)
_NON_METEG_AOM_MARKS = frozenset(mark for mark in ucc.ACCENTS if mark != hpo.MTGOSLQ)
_HATAF_ZWJ_METEG_OPTIONAL_MARKS = frozenset((ha.DEX, ha.GER_M))
_INITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES = frozenset(
    (
        (ha.MUN, ha.DEX),
        (hpo.MTGOSLQ, ha.TEL_G),
        (hpo.MTGOSLQ, ha.DEX),
        (hpo.MTGOSLQ, ha.GER_M),
        (ha.GER, ha.TEL_G),
        (ha.GER_M, ha.REV),
        (ha.GER_2, ha.TEL_G),
    )
)
_NONINITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES = frozenset(((hpo.MTGOSLQ, ha.OLE),))
_HATAF_VOWELS = frozenset((hpo.XSEGOL, hpo.XPATAX, hpo.XQAMATS))
_PQ_VOWELS = frozenset((hpo.PATAX, hpo.QAMATS))
_XS_VOWELS = frozenset((hpo.XIRIQ, hpo.SHEVA))
_LAMED_BELOW_AOM_MARKS = frozenset((*ha.UNI_UNDER_ACCENTS, hpo.MTGOSLQ))
_CGJ_ONLY = frozenset((sd.CGJ,))
_STRIPPED_MARKS = frozenset((hpu.UPDOT, hpu.LODOT))
_FORMAT_CONTROLS = frozenset((sd.CGJ, sd.ZWJ))
_CLASS_ORDER = (
    "ordinary",
    "explicit-order",
    "initial-double-aom",
    "multi-vowel",
    "noninitial-double-aom",
    "unexpected-mark",
    "other-ordering",
)
_PAGE_EXCLUSIONS = (
    (
        "Extraordinary upper dots and lower dots are stripped before clusters are "
        "classified on this page."
    ),
    (
        "The three dually-cantillated passages are excluded: Exodus 20, "
        "Deuteronomy 5, and Genesis 35:22."
    ),
)
_ORDINARY_PAGE_NOTES = {
    "additional-patterns-intro": (
        "Additional patterns treated as ordinary (after any optional shsi-dot "
        "and optional dms-r):"
    ),
}


@dataclass(frozen=True)
class OrdinaryOverrideRule:
    key: str
    description: str
    matcher: Callable[[dict, int], bool]

    def matches(self, cluster, cluster_idx):
        return self.matcher(cluster, cluster_idx)


@dataclass(frozen=True)
class OrdinaryPatternDisplayItem:
    text: str
    subitems: tuple["OrdinaryPatternDisplayItem", ...] = ()


def init():
    return {
        "summary-counts": {
            "total-clusters": 0,
            "excluded-atoms": 0,
            "ordinary": 0,
            "allowed-overrides": 0,
            "exotic": 0,
        },
        "class-counts": {class_key: 0 for class_key in _CLASS_ORDER},
        "sequence-counts-by-class": {class_key: {} for class_key in _CLASS_ORDER},
        "cases-by-class": {class_key: [] for class_key in _CLASS_ORDER[1:]},
    }


def ordinary_page_notes():
    return _ORDINARY_PAGE_NOTES


def page_exclusions():
    return _PAGE_EXCLUSIONS


def ordinary_override_rules():
    return _ORDINARY_OVERRIDE_RULES


def ordinary_pattern_display_items():
    return _ORDINARY_PATTERN_DISPLAY_ITEMS


def collect_for_verse(fois, bcv, verse):
    if _is_excluded(*bcv):
        fois["summary-counts"]["excluded-atoms"] += len(verse)
        return
    for atidx, atom in enumerate(verse, start=1):
        assert isinstance(atom, list)
        assert len(atom) >= 2
        atom_type, atom_text = atom[:2]
        atom_note_data = _atom_note_data(atom)
        bcvp = *bcv, atidx
        for cluster_idx, cluster in enumerate(
            split_atom_clusters(atom_text, strip_marks=True), start=1
        ):
            _collect_for_cluster(
                fois,
                bcvp,
                atom_type,
                atom_text,
                atom_note_data,
                cluster_idx,
                cluster,
            )


def _is_excluded(bkid, chnu, vrnu):
    return (bkid, chnu) in _DUAL_CANTILLATION_LOCS or (
        bkid,
        chnu,
        vrnu,
    ) in _DUAL_CANTILLATION_LOCS


def _collect_for_cluster(
    fois, bcvp, atom_type, atom_text, atom_note_data, cluster_idx, cluster
):
    summary_counts = fois["summary-counts"]
    summary_counts["total-clusters"] += 1
    cluster_class, status_key = _classify(cluster, cluster_idx)
    summary_counts[status_key] += 1
    fois["class-counts"][cluster_class] += 1
    sequence = _mark_sequence(cluster)
    seq_counts = fois["sequence-counts-by-class"][cluster_class]
    seq_counts[sequence] = seq_counts.get(sequence, 0) + 1
    if cluster_class == "ordinary":
        return
    fois["cases-by-class"][cluster_class].append(
        {
            "bcvp": _bcvp_str(bcvp),
            "notes": _notes_str(atom_note_data),
            "atom": atom_text,
            "atom-note-schematic": _note_schematic(atom_note_data),
            "cluster-index": cluster_idx,
            "cluster": cluster["letter"] + "".join(cluster["marks"]),
            "sequence": sequence,
            "mark-names": ", ".join(my_unicode.name(mark) for mark in cluster["marks"]),
        }
    )


def atom_cluster_ranges(atom_text):
    ranges = []
    current_start = None
    for idx, ch in enumerate(atom_text):
        if ch in ucc.LETTERS:
            if current_start is not None:
                ranges.append((current_start, idx))
            current_start = idx
            continue
        if current_start is not None and unicodedata.category(ch) in ("Mn", "Cf"):
            continue
        if current_start is not None:
            ranges.append((current_start, idx))
            current_start = None
    if current_start is not None:
        ranges.append((current_start, len(atom_text)))
    return tuple(ranges)


def split_atom_clusters(atom_text, strip_marks=False):
    clusters = []
    for start, end in atom_cluster_ranges(atom_text):
        cluster_text = atom_text[start:end]
        cluster = {"letter": cluster_text[0], "marks": []}
        for ch in cluster_text[1:]:
            if strip_marks and ch in _STRIPPED_MARKS:
                continue
            cluster["marks"].append(ch)
        clusters.append(cluster)
    return clusters


def _classify(cluster, cluster_idx):
    marks = cluster["marks"]
    if _unexpected_marks(marks):
        return "unexpected-mark", "exotic"
    if _is_ordinary(cluster, cluster_idx):
        return "ordinary", "ordinary"
    if any(mark in _FORMAT_CONTROLS for mark in marks):
        return "explicit-order", "allowed-overrides"
    if cluster_idx == 1 and _is_initial_double_aom(marks):
        return "initial-double-aom", "allowed-overrides"
    if _mark_sequence(marks).count("v") > 1:
        return "multi-vowel", "exotic"
    if _mark_sequence(marks).count("a") > 1:
        return "noninitial-double-aom", "exotic"
    return "other-ordering", "exotic"


def _is_ordinary(cluster, cluster_idx):
    for ordinary_override_rule in _ORDINARY_OVERRIDE_RULES:
        if ordinary_override_rule.matches(cluster, cluster_idx):
            return True
    marks = cluster["marks"]
    if any(mark in _FORMAT_CONTROLS for mark in marks):
        return False
    sequence = _mark_sequence(marks)
    if not _is_in_nondecreasing_order(sequence):
        return False
    return all(sequence.count(mark_class) <= 1 for mark_class in "sdva")


def _marks_without_format_controls(marks):
    return [mark for mark in marks if mark not in _FORMAT_CONTROLS]


def _is_expected_hataf_zwj_meteg(marks):
    idx = 0
    if idx < len(marks) and marks[idx] in _SHSI_DOT_MARKS:
        idx += 1
    if idx < len(marks) and marks[idx] in _DAGESH_MARKS:
        idx += 1
    if idx + 2 >= len(marks):
        return False
    if marks[idx] not in _HATAF_VOWELS:
        return False
    if marks[idx + 1] != sd.ZWJ or marks[idx + 2] != hpo.MTGOSLQ:
        return False
    trailing_marks = marks[idx + 3 :]
    return len(trailing_marks) <= 1 and all(
        mark in _HATAF_ZWJ_METEG_OPTIONAL_MARKS for mark in trailing_marks
    )


def _is_expected_meteg_cgj_vowel(marks):
    idx = 0
    if idx < len(marks) and marks[idx] in _SHSI_DOT_MARKS:
        idx += 1
    if idx < len(marks) and marks[idx] in _DAGESH_MARKS:
        idx += 1
    if idx + 2 >= len(marks):
        return False
    if marks[idx] != hpo.MTGOSLQ:
        return False
    if marks[idx + 1] not in _CGJ_ONLY or marks[idx + 2] not in _VOWEL_MARKS:
        return False
    trailing_marks = marks[idx + 3 :]
    return len(trailing_marks) <= 1 and all(
        mark in _NON_METEG_AOM_MARKS for mark in trailing_marks
    )


def _is_expected_lamed_pq_cgj_xs(letter, marks):
    if letter != hl.LAMED:
        return False
    if len(marks) == 3:
        return (
            marks[0] in _PQ_VOWELS and marks[1] in _CGJ_ONLY and marks[2] in _XS_VOWELS
        )
    return False


def _is_expected_lamed_pq_below_aom_cgj_xs(letter, marks):
    if letter != hl.LAMED:
        return False
    if len(marks) == 4:
        return (
            marks[0] in _PQ_VOWELS
            and marks[1] in _LAMED_BELOW_AOM_MARKS
            and marks[2] in _CGJ_ONLY
            and marks[3] in _XS_VOWELS
        )
    return False


def _is_expected_lamed_pq_xs_maybe_above_aom(letter, marks):
    if letter != hl.LAMED:
        return False
    if len(marks) == 2:
        return marks[0] in _PQ_VOWELS and marks[1] in _XS_VOWELS
    if len(marks) == 3:
        return (
            marks[0] in _PQ_VOWELS
            and marks[1] in _XS_VOWELS
            and marks[2] in ha.UNI_OVER_ACCENTS
        )
    return False


def _has_expected_ordinary_double_aom_prefix(marks):
    prefix = marks[:-2]
    sequence = _mark_sequence(prefix)
    return _is_in_nondecreasing_order(sequence) and all(
        sequence.count(mark_class) <= 1 for mark_class in "sdv"
    )


def _is_expected_initial_double_aom_suffix(marks, cluster_idx):
    if len(marks) < 2:
        return False
    if cluster_idx != 1:
        return False
    if tuple(marks[-2:]) not in _INITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES:
        return False
    return _has_expected_ordinary_double_aom_prefix(marks)


def _is_expected_noninitial_double_aom_suffix(marks):
    if len(marks) < 2:
        return False
    if tuple(marks[-2:]) not in _NONINITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES:
        return False
    return _has_expected_ordinary_double_aom_prefix(marks)


def _matches_meteg_cgj_vowel(cluster, cluster_idx):
    return _is_expected_meteg_cgj_vowel(cluster["marks"])


def _matches_lamed_pq_cgj_xs(cluster, cluster_idx):
    return _is_expected_lamed_pq_cgj_xs(cluster["letter"], cluster["marks"])


def _matches_lamed_pq_below_aom_cgj_xs(cluster, cluster_idx):
    return _is_expected_lamed_pq_below_aom_cgj_xs(cluster["letter"], cluster["marks"])


def _matches_lamed_pq_xs_maybe_above_aom(cluster, cluster_idx):
    return _is_expected_lamed_pq_xs_maybe_above_aom(cluster["letter"], cluster["marks"])


def _matches_hataf_zwj_meteg(cluster, cluster_idx):
    return _is_expected_hataf_zwj_meteg(cluster["marks"])


def _matches_initial_double_aom_suffix(cluster, cluster_idx):
    if any(mark in _FORMAT_CONTROLS for mark in cluster["marks"]):
        return False
    return _is_expected_initial_double_aom_suffix(cluster["marks"], cluster_idx)


def _matches_noninitial_double_aom_suffix(cluster, cluster_idx):
    if any(mark in _FORMAT_CONTROLS for mark in cluster["marks"]):
        return False
    return _is_expected_noninitial_double_aom_suffix(cluster["marks"])


_ORDINARY_OVERRIDE_RULES = (
    OrdinaryOverrideRule(
        "meteg-cgj-vowel",
        "meteg, CGJ, vowel, with an optional trailing non-meteg accent.",
        _matches_meteg_cgj_vowel,
    ),
    OrdinaryOverrideRule(
        "lamed-pq-cgj-xs",
        "On lamed only: pq-vowel, CGJ, xs-vowel.",
        _matches_lamed_pq_cgj_xs,
    ),
    OrdinaryOverrideRule(
        "lamed-pq-below-aom-cgj-xs",
        "On lamed only: pq-vowel, ba-is, CGJ, xs-vowel.",
        _matches_lamed_pq_below_aom_cgj_xs,
    ),
    OrdinaryOverrideRule(
        "lamed-pq-xs-maybe-above-aom",
        "On lamed only: pq-vowel, xs-vowel, with optional above-accent.",
        _matches_lamed_pq_xs_maybe_above_aom,
    ),
    OrdinaryOverrideRule(
        "hataf-zwj-meteg",
        "One of the three ḥataf vowels, then ZWJ, then meteg, then, optionally, deḥi or geresh muqdam.",
        _matches_hataf_zwj_meteg,
    ),
    OrdinaryOverrideRule(
        "initial-double-aom-suffix",
        "On the first letter of a word only: munaḥ then deḥi; meteg then telisha gedolah, deḥi, or geresh muqdam; geresh or gershayim then telisha gedolah; or geresh muqdam then revia.",
        _matches_initial_double_aom_suffix,
    ),
    OrdinaryOverrideRule(
        "noninitial-double-aom-suffix",
        "On any letter: meteg followed by oleh.",
        _matches_noninitial_double_aom_suffix,
    ),
)

_ORDINARY_PATTERN_DISPLAY_ITEMS = (
    OrdinaryPatternDisplayItem(
        "meteg, CGJ, vowel, with an optional trailing non-meteg accent."
    ),
    OrdinaryPatternDisplayItem(
        "On lamed only:",
        (
            OrdinaryPatternDisplayItem("pq-vowel, optional ba-is, CGJ, xs-vowel."),
            OrdinaryPatternDisplayItem(
                "pq-vowel, xs-vowel, with optional above-accent."
            ),
        ),
    ),
    OrdinaryPatternDisplayItem(
        "One of the three ḥataf vowels, then ZWJ, then meteg, then, optionally, deḥi or geresh muqdam."
    ),
    OrdinaryPatternDisplayItem(
        "On the first letter of a word only:",
        (
            OrdinaryPatternDisplayItem("munaḥ then deḥi."),
            OrdinaryPatternDisplayItem(
                "meteg then telisha gedolah, deḥi, or geresh muqdam."
            ),
            OrdinaryPatternDisplayItem("geresh or gershayim then telisha gedolah."),
            OrdinaryPatternDisplayItem("geresh muqdam then revia."),
        ),
    ),
    OrdinaryPatternDisplayItem("On any letter: meteg followed by oleh."),
)


def _is_initial_double_aom(marks):
    sequence = _mark_sequence(marks)
    if not sequence.endswith("aa"):
        return False
    prefix = sequence[:-2]
    return _is_in_nondecreasing_order(prefix) and all(
        prefix.count(mark_class) <= 1 for mark_class in "sdv"
    )


def _is_in_nondecreasing_order(sequence):
    sort_order = {"s": 0, "d": 1, "v": 2, "a": 3}
    last = -1
    for mark_class in sequence:
        current = sort_order[mark_class]
        if current < last:
            return False
        last = current
    return True


def _unexpected_marks(marks):
    return [mark for mark in marks if _mark_class(mark) == "?"]


def _mark_sequence(cluster_or_marks):
    marks = (
        cluster_or_marks["marks"]
        if isinstance(cluster_or_marks, dict)
        else cluster_or_marks
    )
    return "".join(_mark_class(mark) for mark in marks if _mark_class(mark) != "f")


def _mark_class(mark):
    if mark in _SHSI_DOT_MARKS:
        return "s"
    if mark in _DAGESH_MARKS:
        return "d"
    if mark in _VOWEL_MARKS:
        return "v"
    if mark in _AOM_MARKS:
        return "a"
    if mark in _FORMAT_CONTROLS:
        return "f"
    return "?"


def _atom_note_data(atom):
    if len(atom) < 3:
        return None
    note_data = atom[2]
    if not note_data["types"]:
        return None
    return note_data


def _notes_str(atom_note_data):
    if atom_note_data is None:
        return ""
    return ",".join(atom_note_data["types"])


def _note_schematic(atom_note_data):
    if atom_note_data is None:
        return None
    return atom_note_data["schematic"]


def _bcvp_str(bcvp):
    bkid, chnu, vrnu, atnu = bcvp
    return f"{bkid} {chnu}:{vrnu}.{atnu}"
