# Initially generated by GitHub Copilot.
"""Exports write, summary."""

from pathlib import PurePosixPath

import py_misc.my_html as my_html


_MARK_CLASS_ORDER = (
    "ordinary",
    "explicit-order",
    "initial-double-aom",
    "multi-vowel",
    "noninitial-double-aom",
    "unexpected-mark",
    "other-ordering",
)
_MARK_CASE_HEADERS = (
    "bcvp",
    "atom-type",
    "atom",
    "cluster",
    "sequence",
    "mark-names",
)


def summary(mark_catalog):
    summary_counts = mark_catalog["summary-counts"]
    return (
        f"{summary_counts['total-clusters']} clusters; "
        f"{summary_counts['allowed-overrides']} allowed overrides; "
        f"{summary_counts['exotic']} exotic clusters"
    )


def write(mark_catalog, json_output_path, out_path):
    summary_counts = mark_catalog["summary-counts"]
    body_contents = _body_wrapper(
        [
            my_html.heading_level_1("mark-grammar (UXLC features of interest)"),
            my_html.para(
                "This page classifies Hebrew letter clusters against the ordinary mark grammar sla -> dagesh -> vowel -> aom."
            ),
            my_html.para(
                "The three dually-cantillated passages are excluded: Exodus 20, Deuteronomy 5, and Genesis 35:22."
            ),
            my_html.para(
                f"There are {summary_counts['total-clusters']} included clusters; "
                f"{summary_counts['ordinary']} are ordinary, "
                f"{summary_counts['allowed-overrides']} are treated as allowed overrides, "
                f"and {summary_counts['exotic']} remain exotic."
            ),
            my_html.para(
                [
                    my_html.anchor("FOI index", {"href": "index.html"}),
                    " | ",
                    *_json_link_contents(json_output_path),
                ]
            ),
            my_html.heading_level_2("Counts by class"),
            _class_counts_table(mark_catalog),
            *_sections(mark_catalog),
        ]
    )
    _write_html("mark-grammar (UXLC features of interest)", out_path, body_contents)


def _class_counts_table(mark_catalog):
    rows = [my_html.table_row_of_headers(("class", "status", "count", "details"))]
    for class_key in _MARK_CLASS_ORDER:
        rows.append(_class_count_row(class_key, mark_catalog))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _class_count_row(class_key, mark_catalog):
    count = mark_catalog["class-counts"][class_key]
    if class_key == "ordinary":
        detail_contents = "Counted only; not listed below"
    else:
        detail_contents = my_html.anchor(
            f"{len(mark_catalog['cases-by-class'][class_key])} cases",
            {"href": f"#{_section_id(class_key)}"},
        )
    return my_html.table_row_of_data(
        (
            _class_label(class_key),
            _status_label(class_key),
            str(count),
            detail_contents,
        )
    )


def _sections(mark_catalog):
    sections = []
    for class_key in _MARK_CLASS_ORDER[1:]:
        sections.extend(_section(class_key, mark_catalog))
    return sections


def _section(class_key, mark_catalog):
    cases = mark_catalog["cases-by-class"][class_key]
    heading = my_html.heading_level_2(
        f"{_class_label(class_key)} ({len(cases)} cases)",
        {"id": _section_id(class_key)},
    )
    return [
        heading,
        _sequence_counts_table(mark_catalog["sequence-counts-by-class"][class_key]),
        _cases_table(cases),
    ]


def _sequence_counts_table(sequence_counts):
    rows = [my_html.table_row_of_headers(("sequence", "count"))]
    for sequence, count in sorted(
        sequence_counts.items(), key=lambda item: (-item[1], item[0])
    ):
        rows.append(my_html.table_row_of_data((_sequence_label(sequence), str(count))))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _cases_table(cases):
    rows = [my_html.table_row_of_headers(_MARK_CASE_HEADERS)]
    rows.extend(_case_row(case_dic) for case_dic in cases)
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _case_row(case_dic):
    row_cells = []
    for field_name in _MARK_CASE_HEADERS:
        cell_value = case_dic[field_name]
        if field_name in ("atom", "cluster"):
            row_cells.append(
                my_html.table_datum(cell_value, {"lang": "hbo", "dir": "rtl"})
            )
            continue
        if field_name == "sequence":
            row_cells.append(my_html.table_datum(_sequence_label(cell_value)))
            continue
        row_cells.append(my_html.table_datum(cell_value))
    return my_html.table_row(tuple(row_cells))


def _class_label(class_key):
    return {
        "ordinary": "ordinary",
        "explicit-order": "explicit-order",
        "initial-double-aom": "initial-double-aom",
        "multi-vowel": "multi-vowel",
        "noninitial-double-aom": "noninitial-double-aom",
        "unexpected-mark": "unexpected-mark",
        "other-ordering": "other-ordering",
    }[class_key]


def _status_label(class_key):
    if class_key == "ordinary":
        return "ordinary"
    if class_key in ("explicit-order", "initial-double-aom"):
        return "allowed override"
    return "exotic"


def _sequence_label(sequence):
    return sequence or "(bare-letter)"


def _section_id(class_key):
    return f"intro-{class_key}"


def _json_link_contents(json_output_path):
    return [
        "JSON catalog: ",
        my_html.anchor(
            _json_basename(json_output_path),
            {"href": _json_basename(json_output_path)},
        ),
    ]


def _json_basename(json_output_path):
    return PurePosixPath(json_output_path).name


def _body_wrapper(contents):
    style = "max-width: 50rem; margin-left: auto; margin-right: auto"
    return [my_html.div(contents, {"style": style})]


def _write_html(title, out_path, body_contents):
    write_ctx = my_html.WriteCtx(title, out_path)
    my_html.write_html_to_file(body_contents, write_ctx, "../")
