# Initially generated by GitHub Copilot.
"""Exports summary, write."""

from pathlib import PurePosixPath
import re

import py_misc.my_html as my_html
import py_fois.fois_mark_name_abbrev as fois_mark_name_abbrev
import py_fois.fois_mark_grammar_2_foi as fois_mark_grammar_2_foi
import py_fois.fois_mark_grammar_foi as fois_mark_grammar_foi


_CASE_HEADERS = ("bcvp", "notes", "atom", "sequence", "count", "mark names")
_CASE_HEADER_LABELS = {
    "bcvp": "bcvp",
    "notes": "n",
    "atom": "atom",
    "sequence": "seq",
    "count": "count",
    "mark names": "mark names",
}
_CASE_HEADER_TOOLTIPS = {
    "notes": "notes",
    "sequence": "sequence, ignoring shsi-dot and dms",
    "count": "count with this mark names value in this category, ignoring shsi-dot and dms",
}
_ABBREVIATION_TOOLTIP_TITLES = {
    "aom": "accent or meteg",
    **{abbr: meaning for abbr, meaning in fois_mark_grammar_2_foi.abbreviation_rows()},
}
_ABBREVIATION_TOOLTIP_PATTERN = re.compile(
    "|".join(
        re.escape(abbreviation)
        for abbreviation in sorted(_ABBREVIATION_TOOLTIP_TITLES, key=len, reverse=True)
    )
)


def _count_str(value):
    return f"{value:,}"


def summary(catalog):
    tracked_clusters = catalog["summary-counts"]["tracked-clusters"]
    leaf_bucket_count = len(fois_mark_grammar_2_foi.leaf_bucket_specs())
    return (
        f"{_count_str(tracked_clusters)} tracked treated-ordinary clusters across "
        f"{leaf_bucket_count + 1} buckets"
    )


def write(catalog, json_output_path, out_path):
    treated_ordinary_bucket = catalog["treated-ordinary-bucket"]
    leaf_buckets = catalog["leaf-buckets"]
    body_items = [
        my_html.heading_level_1("mark grammar 2 (UXLC features of interest)"),
        my_html.para(
            [
                my_html.anchor("FOI index", {"href": "index.html"}),
                " | ",
                my_html.anchor("mark grammar", {"href": "foi-mark-grammar.html"}),
                " | ",
                *_json_link_contents(json_output_path),
            ]
        ),
        my_html.para(
            "This page lists the Hebrew letter clusters that are not ordinary, "
            "but treated as ordinary."
        ),
        my_html.heading_level_2("Abbreviations"),
        _abbreviation_table(),
        my_html.heading_level_2("Patterns treated as ordinary"),
        my_html.para(
            _tooltipify_abbreviations(
                fois_mark_grammar_2_foi.additional_patterns_intro()
            )
        ),
        _ordinary_pattern_display_list(
            fois_mark_grammar_2_foi.additional_pattern_display_items()
        ),
        my_html.heading_level_2("Counts"),
        _counts_table(catalog),
        *_bucket_section(
            treated_ordinary_bucket,
            "treated-ordinary-rafeh",
        ),
    ]
    for spec in fois_mark_grammar_2_foi.leaf_bucket_specs():
        body_items.extend(_bucket_section(leaf_buckets[spec["key"]], spec["key"]))
    body_contents = _body_wrapper(body_items)
    _write_html("mark grammar 2 (UXLC features of interest)", out_path, body_contents)


def _abbreviation_table():
    rows = [my_html.table_row_of_headers(("abbreviation", "meaning"))]
    rows.extend(
        my_html.table_row(
            (
                my_html.table_datum(abbreviation),
                my_html.table_datum(
                    _abbreviation_meaning_contents(abbreviation, meaning)
                ),
            )
        )
        for abbreviation, meaning in fois_mark_grammar_2_foi.abbreviation_rows()
    )
    rows.append(my_html.table_row_of_data(("aom", "accent or meteg")))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _abbreviation_meaning_contents(abbreviation, meaning):
    if abbreviation != "pre-wm":
        return meaning
    prefix, suffix = meaning.split(": ", maxsplit=1)
    return (prefix + ":", my_html.line_break(), suffix)


def _ordinary_pattern_display_list(display_items):
    return my_html.unordered_list(
        tuple(
            _ordinary_pattern_display_list_item(display_item)
            for display_item in display_items
        )
    )


def _ordinary_pattern_display_list_item(display_item):
    text = _tooltipify_abbreviations(display_item.text)
    if not display_item.subitems:
        return text
    if isinstance(text, str):
        return (text, _ordinary_pattern_display_list(display_item.subitems))
    return (*text, _ordinary_pattern_display_list(display_item.subitems))


def _counts_table(catalog):
    rows = [my_html.table_row_of_headers(("pattern", "count", "details"))]
    treated_ordinary_bucket = catalog["treated-ordinary-bucket"]
    rows.append(_count_row(treated_ordinary_bucket))
    for spec in fois_mark_grammar_2_foi.leaf_bucket_specs():
        rows.append(_count_row(catalog["leaf-buckets"][spec["key"]]))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _count_row(bucket):
    return my_html.table_row_of_data(
        (
            _tooltipify_abbreviations(bucket["label"]),
            _count_str(bucket["count"]),
            my_html.anchor("details", {"href": f"#{_section_id(bucket['key'])}"}),
        )
    )


def _bucket_section(bucket, bucket_key):
    contents = [
        my_html.heading_level_2(
            f"{bucket['label']} ({_count_str(bucket['count'])} total)",
            {"id": _section_id(bucket_key)},
        )
    ]
    fork_buckets = bucket.get("fork-buckets")
    if not fork_buckets:
        contents.extend(
            (_bucket_example_intro(bucket), _cases_table(bucket["examples"]))
        )
        return contents
    for fork_bucket in fork_buckets.values():
        contents.extend(_fork_section(fork_bucket, bucket_key))
    return contents


def _bucket_example_intro(bucket):
    shown_count = len(bucket["examples"])
    return my_html.para(
        f"Showing {shown_count} distinct mark-names value"
        f"{'s' if shown_count != 1 else ''} across "
        f"{_count_str(bucket['count'])} total clusters, ignoring shsi-dot and dms "
        f"for diversity."
    )


def _fork_section(fork_bucket, bucket_key):
    return [
        my_html.heading_level_3(
            f"{fork_bucket['label']} ({_count_str(fork_bucket['count'])} total)",
            {"id": _fork_section_id(fork_bucket["key"], bucket_key)},
        ),
        _bucket_example_intro(fork_bucket),
        _cases_table(fork_bucket["examples"]),
    ]


def _cases_table(cases):
    rows = [
        my_html.table_row_of_headers(
            tuple(_case_header_label(field_name) for field_name in _CASE_HEADERS)
        )
    ]
    rows.extend(_case_row(case_dic) for case_dic in cases)
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _case_row(case_dic):
    row_cells = []
    for field_name in _CASE_HEADERS:
        if field_name == "atom":
            row_cells.append(
                my_html.table_datum(
                    _highlighted_atom(case_dic), {"lang": "hbo", "dir": "rtl"}
                )
            )
            continue
        if field_name == "mark names":
            row_cells.append(my_html.table_datum(_mark_names_cell_contents(case_dic)))
            continue
        if field_name == "count":
            row_cells.append(my_html.table_datum(_count_str(case_dic[field_name])))
            continue
        row_cells.append(my_html.table_datum(case_dic[field_name]))
    return my_html.table_row(tuple(row_cells))


def _mark_names_cell_contents(case_dic):
    return _tooltipify_abbreviations(
        fois_mark_name_abbrev.abbreviate_mark_names(case_dic["mark names"])
    )


def _case_header_label(field_name):
    label = _CASE_HEADER_LABELS[field_name]
    if field_name not in _CASE_HEADER_TOOLTIPS:
        return label
    return my_html.span(
        label,
        {
            "class": "abbrev-tooltip",
            "title": _CASE_HEADER_TOOLTIPS[field_name],
        },
    )


def _highlighted_atom(case_dic):
    return _highlighted_atom_contents(case_dic["atom"], case_dic["cluster-index"])


def _highlighted_atom_contents(atom_text, target_cluster):
    cluster_ranges = fois_mark_grammar_foi.atom_cluster_ranges(atom_text)
    row_contents = []
    cursor = 0
    for cluster_idx, (start, end) in enumerate(cluster_ranges, start=1):
        if cursor < start:
            row_contents.append(atom_text[cursor:start])
        cluster_text = atom_text[start:end]
        if cluster_idx == target_cluster:
            row_contents.append(
                my_html.span(cluster_text, {"class": "cluster-highlight"})
            )
        else:
            row_contents.append(cluster_text)
        cursor = end
    if cursor < len(atom_text):
        row_contents.append(atom_text[cursor:])
    return tuple(row_contents)


def _tooltipify_abbreviations(text):
    parts = []
    last_end = 0
    for match in _ABBREVIATION_TOOLTIP_PATTERN.finditer(text):
        if last_end < match.start():
            parts.append(text[last_end : match.start()])
        abbreviation = match.group(0)
        parts.append(
            my_html.span(
                abbreviation,
                {
                    "class": "abbrev-tooltip",
                    "title": _ABBREVIATION_TOOLTIP_TITLES[abbreviation],
                },
            )
        )
        last_end = match.end()
    if not parts:
        return text
    if last_end < len(text):
        parts.append(text[last_end:])
    return tuple(parts)


def _section_id(bucket_key):
    return f"bucket-{bucket_key}"


def _fork_section_id(fork_key, bucket_key=None):
    if bucket_key is None:
        return f"fork-{fork_key}"
    return f"fork-{bucket_key}-{fork_key}"


def _json_link_contents(json_output_path):
    return [
        "JSON catalog: ",
        my_html.anchor(
            _json_basename(json_output_path),
            {"href": _json_basename(json_output_path)},
        ),
    ]


def _json_basename(json_output_path):
    return PurePosixPath(json_output_path).name


def _body_wrapper(contents):
    style = "max-width: 50rem; margin-left: auto; margin-right: auto"
    return [my_html.div(contents, {"style": style})]


def _write_html(title, out_path, body_contents):
    write_ctx = my_html.WriteCtx(title, out_path)
    my_html.write_html_to_file(body_contents, write_ctx, "../")
