# Initially generated by GitHub Copilot.
"""Exports write, summary."""

from pathlib import PurePosixPath
import re

import py_misc.my_html as my_html
import py_fois.fois_mark_grammar_foi as fois_mark_grammar_foi


_MARK_CLASS_ORDER = (
    "ordinary",
    "explicit-order",
    "initial-double-aom",
    "multi-vowel",
    "noninitial-double-aom",
    "unexpected-mark",
    "other-ordering",
)
_MARK_CASE_HEADERS = (
    "bcvp",
    "notes",
    "atom",
    "sequence",
    "mark-names",
)
_GRAMMAR_ORDER_ROWS = (
    ("shsi-dot", "shin-dot or sin-dot"),
    ("dms-r", "dms (see below) or rafeh"),
    ("vowel", ""),
    ("aom", "accent or meteg"),
)
_ABBREVIATION_ROWS = (
    ("dms", "dagesh/mapiq/shuruq-dot"),
    ("ba-is", "below-accents including silluq"),
    ("metuq", "meteg/siluq"),
    ("CGJ", "combining grapheme joiner"),
    ("ZWJ", "zero-width joiner"),
    ("xataf", "one of the three ḥataf vowels"),
    ("pq-vowel", "pataḥ or qamats"),
    ("xs-vowel", "ḥiriq or sheva"),
)

_PRE_WM_ABBREVIATION_ROW = (
    "pre-wm",
    (
        "prepositive that can occur with meteg:",
        my_html.line_break(),
        "telisha gedolah, deḥi, geresh muqdam",
    ),
)
_ABBREVIATION_TOOLTIP_TITLES = {
    "shsi-dot": "shin-dot or sin-dot",
    "dms-r": "dms (see below) or rafeh",
    "dms": "dagesh/mapiq/shuruq-dot",
    "ba-is": "below-accents including silluq",
    "metuq": "meteg/siluq",
    "CGJ": "combining grapheme joiner",
    "ZWJ": "zero-width joiner",
    "xataf": "one of the three ḥataf vowels",
    "pq-vowel": "pataḥ or qamats",
    "xs-vowel": "ḥiriq or sheva",
    "pre-wm": "prepositive that can occur with meteg: telisha gedolah, deḥi, geresh muqdam",
}
_ABBREVIATION_TOOLTIP_PATTERN = re.compile(
    "|".join(
        re.escape(abbreviation)
        for abbreviation in sorted(_ABBREVIATION_TOOLTIP_TITLES, key=len, reverse=True)
    )
)
_BCVP_PATTERN = re.compile(
    r"^(?P<book>.+) (?P<chapter>\d+):(?P<verse>\d+)\.(?P<atom>\d+)$"
)
_TANACH_US_BOOK_CODES = {
    "Genesis": "Gen",
    "Exodus": "Ex",
    "Levit": "Lev",
    "Numbers": "Num",
    "Deuter": "Deut",
    "Joshua": "Josh",
    "Judges": "Judg",
    "1Samuel": "1Sam",
    "2Samuel": "2Sam",
    "1Kings": "1Kings",
    "2Kings": "2Kings",
    "Isaiah": "Isa",
    "Jeremiah": "Jer",
    "Ezekiel": "Ezek",
    "Hosea": "Hos",
    "Joel": "Joel",
    "Amos": "Am",
    "Obadiah": "Ob",
    "Jonah": "Jon",
    "Micah": "Mic",
    "Nahum": "Nah",
    "Habakkuk": "Hab",
    "Tsefaniah": "Zeph",
    "Haggai": "Hag",
    "Zechariah": "Zech",
    "Malachi": "Mal",
    "Psalms": "Ps",
    "Proverbs": "Prov",
    "Job": "Job",
    "Song of Songs": "Song",
    "Ruth": "Ruth",
    "Lamentations": "Lam",
    "Ecclesiastes": "Eccl",
    "Esther": "Esth",
    "Daniel": "Dan",
    "Ezra": "Ezra",
    "Nehemiah": "Neh",
    "1Chronicles": "1Chr",
    "2Chronicles": "2Chr",
}


def _count_str(value):
    return f"{value:,}"


def summary(mark_catalog):
    summary_counts = mark_catalog["summary-counts"]
    return (
        f"{_count_str(summary_counts['total-clusters'])} clusters; "
        f"{_count_str(summary_counts['ordinary'])} ordinary; "
        f"{_count_str(summary_counts['total-clusters'] - summary_counts['ordinary'])} listed below"
    )


def write(mark_catalog, json_output_path, out_path):
    summary_counts = mark_catalog["summary-counts"]
    ordinary_page_notes = fois_mark_grammar_foi.ordinary_page_notes()
    page_exclusions = fois_mark_grammar_foi.page_exclusions()
    ordinary_pattern_display_items = (
        fois_mark_grammar_foi.ordinary_pattern_display_items()
    )
    body_contents = _body_wrapper(
        [
            my_html.heading_level_1("mark-grammar (UXLC features of interest)"),
            my_html.para(
                [
                    my_html.anchor("FOI index", {"href": "index.html"}),
                    " | ",
                    *_json_link_contents(json_output_path),
                ]
            ),
            my_html.para(
                "This page classifies Hebrew letter clusters against the ordinary mark grammar:"
            ),
            _grammar_order_table(),
            my_html.heading_level_2("Abbreviations"),
            _abbreviation_table(),
            my_html.para("Exclusions:"),
            my_html.unordered_list(page_exclusions),
            my_html.para(
                _tooltipify_abbreviations(
                    ordinary_page_notes["additional-patterns-intro"]
                )
            ),
            _ordinary_pattern_display_list(ordinary_pattern_display_items),
            my_html.para(
                f"There are {_count_str(summary_counts['total-clusters'])} included "
                f"clusters; {_count_str(summary_counts['ordinary'])} are ordinary, "
                f"and {_count_str(summary_counts['total-clusters'] - summary_counts['ordinary'])} "
                f"fall into the listed non-ordinary classes below."
            ),
            my_html.heading_level_2("Counts by class"),
            _class_counts_table(mark_catalog),
            *_sections(mark_catalog),
        ]
    )
    _write_html("mark-grammar (UXLC features of interest)", out_path, body_contents)


def _ordinary_pattern_display_list(display_items):
    return my_html.unordered_list(
        tuple(
            _ordinary_pattern_display_list_item(display_item)
            for display_item in display_items
        )
    )


def _ordinary_pattern_display_list_item(display_item):
    text = _tooltipify_abbreviations(display_item.text)
    if not display_item.subitems:
        return text
    if isinstance(text, str):
        return (text, _ordinary_pattern_display_list(display_item.subitems))
    return (*text, _ordinary_pattern_display_list(display_item.subitems))


def _class_counts_table(mark_catalog):
    rows = [my_html.table_row_of_headers(("class", "count", "details"))]
    for class_key in _MARK_CLASS_ORDER[1:]:
        rows.append(_class_count_row(class_key, mark_catalog))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _class_count_row(class_key, mark_catalog):
    count = mark_catalog["class-counts"][class_key]
    detail_contents = my_html.anchor(
        f"{_count_str(len(mark_catalog['cases-by-class'][class_key]))} cases",
        {"href": f"#{_section_id(class_key)}"},
    )
    return my_html.table_row_of_data(
        (
            _class_label(class_key),
            _count_str(count),
            detail_contents,
        )
    )


def _sections(mark_catalog):
    sections = []
    for class_key in _MARK_CLASS_ORDER[1:]:
        sections.extend(_section(class_key, mark_catalog))
    return sections


def _section(class_key, mark_catalog):
    cases = mark_catalog["cases-by-class"][class_key]
    heading = my_html.heading_level_2(
        f"{_class_label(class_key)} ({_count_str(len(cases))} cases)",
        {"id": _section_id(class_key)},
    )
    return [
        heading,
        _cases_table(cases),
    ]


def _abbreviation_table():
    rows = [my_html.table_row_of_headers(("abbreviation", "meaning"))]
    rows.extend(my_html.table_row_of_data(row) for row in _ABBREVIATION_ROWS)
    rows.append(my_html.table_row_of_data(_PRE_WM_ABBREVIATION_ROW))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _grammar_order_table():
    rows = [my_html.table_row_of_headers(("item", "meaning"))]
    rows.extend(
        my_html.table_row(
            (
                my_html.table_datum(item),
                my_html.table_datum(_tooltipify_abbreviations(meaning)),
            )
        )
        for item, meaning in _GRAMMAR_ORDER_ROWS
    )
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _cases_table(cases):
    rows = [my_html.table_row_of_headers(_MARK_CASE_HEADERS)]
    rows.extend(_case_row(case_dic) for case_dic in cases)
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _highlighted_atom(case_dic):
    atom_text = case_dic["atom"]
    cluster_ranges = fois_mark_grammar_foi.atom_cluster_ranges(atom_text)
    target_cluster = case_dic["cluster-index"]
    row_contents = []
    cursor = 0
    for cluster_idx, (start, end) in enumerate(cluster_ranges, start=1):
        if cursor < start:
            row_contents.append(atom_text[cursor:start])
        cluster_text = atom_text[start:end]
        if cluster_idx == target_cluster:
            row_contents.append(
                my_html.span(cluster_text, {"class": "cluster-highlight"})
            )
        else:
            row_contents.append(cluster_text)
        cursor = end
    if cursor < len(atom_text):
        row_contents.append(atom_text[cursor:])
    return tuple(row_contents)


def _case_row(case_dic):
    row_cells = []
    for field_name in _MARK_CASE_HEADERS:
        cell_value = case_dic[field_name]
        if field_name == "bcvp":
            row_cells.append(my_html.table_datum(_linked_bcvp(cell_value)))
            continue
        if field_name == "atom":
            row_cells.append(
                my_html.table_datum(
                    _highlighted_atom(case_dic), {"lang": "hbo", "dir": "rtl"}
                )
            )
            continue
        if field_name == "sequence":
            row_cells.append(my_html.table_datum(_sequence_label(cell_value)))
            continue
        if field_name == "mark-names":
            row_cells.append(my_html.table_datum(_abbreviate_mark_names(cell_value)))
            continue
        row_cells.append(my_html.table_datum(cell_value))
    return my_html.table_row(tuple(row_cells))


def _abbreviate_mark_names(mark_names):
    abbreviated = (
        mark_names.replace("dagesh/mapiq/shuruq-dot", "dms")
        .replace("meteg/siluq", "metuq")
        .replace("combining-grapheme-joiner", "CGJ")
        .replace("zero-width-joiner", "ZWJ")
    )
    return _tooltipify_abbreviations(abbreviated)


def _tooltipify_abbreviations(text):
    parts = []
    last_end = 0
    for match in _ABBREVIATION_TOOLTIP_PATTERN.finditer(text):
        if last_end < match.start():
            parts.append(text[last_end : match.start()])
        abbreviation = match.group(0)
        parts.append(
            my_html.span(
                abbreviation,
                {
                    "class": "abbrev-tooltip",
                    "title": _ABBREVIATION_TOOLTIP_TITLES[abbreviation],
                },
            )
        )
        last_end = match.end()
    if not parts:
        return text
    if last_end < len(text):
        parts.append(text[last_end:])
    return tuple(parts)


def _linked_bcvp(bcvp_str):
    match = _BCVP_PATTERN.fullmatch(bcvp_str)
    if match is None:
        return bcvp_str
    book = match.group("book")
    chapter = match.group("chapter")
    verse = match.group("verse")
    atom = match.group("atom")
    bcv_str = f"{_tanach_us_book_code(book)} {chapter}:{verse}"
    return (
        my_html.anchor(
            bcv_str,
            {"href": _tanach_us_bcv_url(book, chapter, verse)},
        ),
        f".{atom}",
    )


def _tanach_us_book_code(book):
    return _TANACH_US_BOOK_CODES[book]


def _tanach_us_bcv_url(book, chapter, verse):
    return f"https://tanach.us/Tanach.xml?{_tanach_us_book_code(book)}{chapter}:{verse}"


def _class_label(class_key):
    return {
        "ordinary": "ordinary",
        "explicit-order": "explicit-order",
        "initial-double-aom": "initial-double-aom",
        "multi-vowel": "multi-vowel",
        "noninitial-double-aom": "noninitial-double-aom",
        "unexpected-mark": "unexpected-mark",
        "other-ordering": "other-ordering",
    }[class_key]


def _sequence_label(sequence):
    return sequence or "(bare-letter)"


def _section_id(class_key):
    return f"intro-{class_key}"


def _json_link_contents(json_output_path):
    return [
        "JSON catalog: ",
        my_html.anchor(
            _json_basename(json_output_path),
            {"href": _json_basename(json_output_path)},
        ),
    ]


def _json_basename(json_output_path):
    return PurePosixPath(json_output_path).name


def _body_wrapper(contents):
    style = "max-width: 50rem; margin-left: auto; margin-right: auto"
    return [my_html.div(contents, {"style": style})]


def _write_html(title, out_path, body_contents):
    write_ctx = my_html.WriteCtx(title, out_path)
    my_html.write_html_to_file(body_contents, write_ctx, "../")
