# Initially generated by GitHub Copilot.
"""Collect FOI data for mark grammar 2."""

import py_misc.my_unicode as my_unicode
import py_fois.fois_mark_name_abbrev as fois_mark_name_abbrev
import py_fois.fois_mark_grammar_foi as fois_mark_grammar_foi
from pycmn import hebrew_points as hpo


_TITLE = "mark grammar 2"
_ADDITIONAL_PATTERN_DISPLAY_ITEMS = (
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "Rafeh. optional shsi-dot, rafeh, optional vowel, optional aom."
    ),
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "SD. optional shsi-dot, optional dms, and then:",
        (
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "Early-meteg. meteg, CGJ, vowel, optional pre-wm."
            ),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "Mid-meteg. xataf, ZWJ, meteg, optional pre-wm."
            ),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "Lamed. On lamed only:",
                (
                    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                        "Below. pq-vowel, ba-is, CGJ, xs-vowel."
                    ),
                    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                        "Above. pq-vowel, xs-vowel, optional above-accent."
                    ),
                ),
            ),
        ),
    ),
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "SDV. optional shsi-dot, optional dms, optional vowel, and then:",
        (
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "FL. On the first letter of a word only:",
                (
                    fois_mark_grammar_foi.OrdinaryPatternDisplayItem("munaḥ, deḥi."),
                    fois_mark_grammar_foi.OrdinaryPatternDisplayItem("meteg, pre-wm."),
                    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                        "gerstar-tg. geresh or gershayim, telisha gedolah."
                    ),
                    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                        "rev-mug. geresh muqdam, revia."
                    ),
                ),
            ),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "meteg, oleh. On any letter: meteg, oleh."
            ),
        ),
    ),
)
_ABBREVIATION_ROWS = (
    ("shsi-dot", "shin-dot or sin-dot"),
    ("dms", "dagesh/mapiq/shuruq-dot"),
    ("metuq", "meteg/siluq"),
    ("ba-is", "below-accent (including silluq)"),
    ("CGJ", "combining grapheme joiner"),
    ("ZWJ", "zero-width joiner"),
    ("xataf", "one of the three ḥataf vowels"),
    ("pq-vowel", "pataḥ or qamats"),
    ("xs-vowel", "ḥiriq or sheva"),
    (
        "pre-wm",
        "prepositive that can occur with meteg: telisha gedolah, deḥi, geresh muqdam",
    ),
)
_SHSI_DOT_MARKS = frozenset((hpo.SHIND, hpo.SIND))
_DMS_MARKS = frozenset((hpo.DAGOMOSD,))
_TREATED_ORDINARY_BUCKET_SPEC = {
    "key": "treated-ordinary-rafeh",
    "label": "Treated as ordinary: optional shsi-dot, rafeh, optional vowel, optional aom.",
    "count-label": "Rafeh",
}
_LEAF_BUCKET_SPECS = (
    {
        "key": "meteg-cgj-vowel",
        "label": "meteg, CGJ, vowel, optional pre-wm.",
        "count-label": "SD.Early-meteg",
        "forks": (
            ("without-pre-wm", "without pre-wm"),
            ("with-pre-wm", "with pre-wm"),
        ),
    },
    {
        "key": "hataf-zwj-meteg",
        "label": "xataf, ZWJ, meteg, optional pre-wm.",
        "count-label": "SD.Mid-meteg",
        "forks": (
            ("without-pre-wm", "without pre-wm"),
            ("with-pre-wm", "with pre-wm"),
        ),
    },
    {
        "key": "lamed-pq-cgj-xs",
        "label": "On lamed only: pq-vowel, ba-is, CGJ, xs-vowel.",
        "count-label": "SD.Lamed.Below",
    },
    {
        "key": "lamed-pq-xs-above-aom",
        "label": "On lamed only: pq-vowel, xs-vowel, optional above-accent.",
        "count-label": "SD.Lamed.Above",
        "forks": (
            ("without-above-accent", "without above-accent"),
            ("with-above-accent", "with above-accent"),
        ),
    },
    {
        "key": "initial-munah-dehi",
        "label": "On the first letter of a word only (after an optional vowel): munaḥ, deḥi.",
        "count-label": "SDV.FL.munaḥ, deḥi.",
    },
    {
        "key": "initial-meteg-pre-wm",
        "label": "On the first letter of a word only (after an optional vowel): meteg, pre-wm.",
        "count-label": "SDV.FL.meteg, pre-wm.",
    },
    {
        "key": "initial-geresh-telisha-gedolah",
        "label": "On the first letter of a word only (after an optional vowel): geresh or gershayim, telisha gedolah.",
        "count-label": "SDV.FL.gerstar-tg",
    },
    {
        "key": "initial-geresh-muqdam-revia",
        "label": "On the first letter of a word only (after an optional vowel): geresh muqdam, revia.",
        "count-label": "SDV.FL.rev-mug",
    },
    {
        "key": "noninitial-meteg-oleh",
        "label": "On any letter (after an optional vowel): meteg, oleh.",
        "count-label": "SDV.meteg, oleh",
    },
)


def treated_ordinary_count_label():
    return _TREATED_ORDINARY_BUCKET_SPEC["count-label"]


def leaf_count_label_by_key():
    return {spec["key"]: spec["count-label"] for spec in _LEAF_BUCKET_SPECS}


def title():
    return _TITLE


def additional_pattern_display_items():
    return _ADDITIONAL_PATTERN_DISPLAY_ITEMS


def abbreviation_rows():
    return _ABBREVIATION_ROWS


def treated_ordinary_bucket_spec():
    return _TREATED_ORDINARY_BUCKET_SPEC


def leaf_bucket_specs():
    return _LEAF_BUCKET_SPECS


def init():
    return {
        "summary-counts": {
            "tracked-clusters": 0,
            "treated-ordinary-rafeh": 0,
        },
        "treated-ordinary-bucket": _init_bucket(_TREATED_ORDINARY_BUCKET_SPEC),
        "leaf-buckets": {
            spec["key"]: _init_bucket(spec) for spec in _LEAF_BUCKET_SPECS
        },
    }


def finalize(catalog):
    _finalize_bucket(
        catalog["treated-ordinary-bucket"],
        catalog["treated-ordinary-bucket"]["key"],
    )
    for spec in _LEAF_BUCKET_SPECS:
        bucket = catalog["leaf-buckets"][spec["key"]]
        _finalize_bucket(bucket, spec["key"])
        if "fork-buckets" not in bucket:
            continue
        for fork_key, fork_bucket in bucket["fork-buckets"].items():
            _finalize_bucket(fork_bucket, spec["key"], fork_key)


def collect_for_verse(fois, bcv, verse):
    if fois_mark_grammar_foi.is_excluded(*bcv):
        return
    for atidx, atom in enumerate(verse, start=1):
        assert isinstance(atom, list)
        assert len(atom) >= 2
        atom_text = atom[1]
        atom_note_data = _atom_note_data(atom)
        bcvp = *bcv, atidx
        for cluster_idx, cluster in enumerate(
            fois_mark_grammar_foi.split_atom_clusters(atom_text, strip_marks=True),
            start=1,
        ):
            if fois_mark_grammar_foi.is_treated_ordinary_rafeh(cluster):
                case_dic = _case_dic(
                    bcvp, atom_text, atom_note_data, cluster_idx, cluster
                )
                _record_case(fois["treated-ordinary-bucket"], case_dic)
                fois["summary-counts"]["tracked-clusters"] += 1
                fois["summary-counts"]["treated-ordinary-rafeh"] += 1
                continue
            ordinary_match = fois_mark_grammar_foi.treated_as_ordinary_pattern_match(
                cluster, cluster_idx
            )
            if ordinary_match is None:
                continue
            case_dic = _case_dic(bcvp, atom_text, atom_note_data, cluster_idx, cluster)
            if ordinary_match.leaf_key is None:
                continue
            bucket = fois["leaf-buckets"][ordinary_match.leaf_key]
            _record_case(bucket, case_dic)
            fois["summary-counts"]["tracked-clusters"] += 1
            if ordinary_match.fork_key is None or "fork-buckets" not in bucket:
                continue
            _record_case(bucket["fork-buckets"][ordinary_match.fork_key], case_dic)


def _init_bucket(spec):
    bucket = {
        "key": spec["key"],
        "label": spec["label"],
        "count-label": spec.get("count-label"),
        "count": 0,
        "examples": [],
        "_all-cases": [],
    }
    if "forks" not in spec:
        return bucket
    bucket["fork-buckets"] = {
        fork_key: {
            "key": fork_key,
            "label": fork_label,
            "count": 0,
            "examples": [],
            "_all-cases": [],
        }
        for fork_key, fork_label in spec["forks"]
    }
    return bucket


def _record_case(bucket, case_dic):
    bucket["count"] += 1
    bucket["_all-cases"].append(dict(case_dic))


def _finalize_bucket(bucket, bucket_key, fork_key=None):
    bucket["examples"] = [
        _public_case_dic(case_dic)
        for case_dic in _select_examples(bucket["_all-cases"], bucket_key, fork_key)
    ]
    del bucket["_all-cases"]


def _select_examples(cases, bucket_key, fork_key):
    del bucket_key, fork_key
    counts_by_mark_names = {}
    selected_by_mark_names = {}
    for case_dic in cases:
        display_mark_names = case_dic["_diversity-mark-names"]
        counts_by_mark_names[display_mark_names] = (
            counts_by_mark_names.get(display_mark_names, 0) + 1
        )
        if display_mark_names in selected_by_mark_names:
            continue
        representative = dict(case_dic)
        representative["count"] = 0
        selected_by_mark_names[display_mark_names] = representative
    for display_mark_names, representative in selected_by_mark_names.items():
        representative["count"] = counts_by_mark_names[display_mark_names]
    return sorted(selected_by_mark_names.values(), key=_mark_names_sort_key)


def _mark_names_sort_key(case_dic):
    return tuple(case_dic["mark names"].split(", "))


def _public_case_dic(case_dic):
    return {key: value for key, value in case_dic.items() if not key.startswith("_")}


def _case_dic(bcvp, atom_text, atom_note_data, cluster_idx, cluster):
    mark_names = ", ".join(my_unicode.name(mark) for mark in cluster["marks"])
    diversity_marks = _marks_without_shsi_dot_and_dms(cluster["marks"])
    diversity_mark_names = ", ".join(my_unicode.name(mark) for mark in diversity_marks)
    return {
        "bcvp": _bcvp_str(bcvp),
        "notes": _notes_str(atom_note_data),
        "atom": atom_text,
        "cluster-index": cluster_idx,
        "sequence": fois_mark_grammar_foi.mark_sequence(diversity_marks),
        "mark names": mark_names,
        "count": 0,
        "_diversity-mark-names": fois_mark_name_abbrev.abbreviate_mark_names(
            diversity_mark_names
        ),
    }


def _marks_without_shsi_dot_and_dms(marks):
    idx = 0
    if idx < len(marks) and marks[idx] in _SHSI_DOT_MARKS:
        idx += 1
    if idx < len(marks) and marks[idx] in _DMS_MARKS:
        idx += 1
    return marks[idx:]


def _atom_note_data(atom):
    if len(atom) < 3:
        return None
    note_data = atom[2]
    if not note_data["types"]:
        return None
    return note_data


def _notes_str(atom_note_data):
    if atom_note_data is None:
        return ""
    return ",".join(atom_note_data["types"])


def _bcvp_str(bcvp):
    bkid, chnu, vrnu, atnu = bcvp
    return f"{bkid} {chnu}:{vrnu}.{atnu}"
