# Initially generated by GitHub Copilot.
"""Exports write."""

from pathlib import PurePosixPath

import py_misc.my_html as my_html
import py_fois.fois_mark_grammar_html as fois_mark_grammar_html


_OUT_DIR_PATH = "gh-pages/fois"
_DETAIL_FILENAME_BY_KEY = {
    "kq": "foi-kq.html",
    "mark-grammar": "foi-mark-grammar.html",
}
_KQ_FIELD_HEADERS = ("bcvp", "k1", "k2", "q1", "q2")


def write(fois, json_output_paths):
    """Write HTML pages for the FOI catalog."""
    _write_index(fois, json_output_paths)
    if kq_catalog := fois.get("kq"):
        _write_kq_page(kq_catalog, json_output_paths["kq"])
    if mark_catalog := fois.get("mark-grammar"):
        fois_mark_grammar_html.write(
            mark_catalog,
            json_output_paths["mark-grammar"],
            f"{_OUT_DIR_PATH}/{_DETAIL_FILENAME_BY_KEY['mark-grammar']}",
        )


def _write_index(fois, json_output_paths):
    rows = [my_html.table_row_of_headers(("page", "summary"))]
    for foi_key, catalog in sorted(fois.items()):
        rows.append(_index_row(foi_key, catalog))
    body_contents = _body_wrapper(
        [
            my_html.heading_level_1("UXLC features of interest"),
            my_html.para(
                "This is an HTML view of the FOI catalog generated by py/main_fois.py."
            ),
            my_html.para(_json_catalogs_contents(json_output_paths)),
            my_html.table(rows, {"class": "border-collapse limited-width"}),
        ]
    )
    _write_html(
        "UXLC features of interest", f"{_OUT_DIR_PATH}/index.html", body_contents
    )


def _index_row(foi_key, catalog):
    detail_filename = _DETAIL_FILENAME_BY_KEY.get(foi_key)
    if detail_filename is None:
        page_cell = my_html.table_datum(foi_key)
    else:
        page_cell = my_html.table_datum(
            my_html.anchor(foi_key, {"href": detail_filename})
        )
    summary_cell = my_html.table_datum(_summary_for_catalog(foi_key, catalog))
    return my_html.table_row((page_cell, summary_cell))


def _summary_for_catalog(foi_key, catalog):
    if foi_key == "kq":
        type_counts = catalog["type-counts"]
        total_cases = sum(type_counts.values())
        exotic_cases = len(catalog["exotic-cases-flat"])
        return f"{total_cases} total cases; {exotic_cases} exotic cases"
    if foi_key == "mark-grammar":
        return fois_mark_grammar_html.summary(catalog)
    return "HTML summary not implemented"


def _write_kq_page(kq_catalog, json_output_path):
    body_contents = _body_wrapper(
        [
            my_html.heading_level_1("kq (UXLC features of interest)"),
            my_html.para(
                "Each kNqM label counts a contiguous kere/qere group with N ketiv atoms and M qere atoms."
            ),
            my_html.para(
                f"There are {sum(kq_catalog['type-counts'].values())} total kq cases; "
                f"{len(kq_catalog['exotic-cases-flat'])} are listed below as exotic."
            ),
            my_html.para(
                [
                    my_html.anchor("FOI index", {"href": "index.html"}),
                    " | ",
                    *_json_link_contents(json_output_path),
                ]
            ),
            my_html.heading_level_2("Counts by type"),
            _kq_counts_table(kq_catalog),
            *_kq_sections(kq_catalog),
        ]
    )
    _write_html("kq (UXLC features of interest)", _kq_detail_path(), body_contents)


def _kq_counts_table(kq_catalog):
    rows = [my_html.table_row_of_headers(("type", "count", "details"))]
    for kq_type, count in kq_catalog["type-counts"].items():
        rows.append(_kq_count_row(kq_type, count, kq_catalog))
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _kq_count_row(kq_type, count, kq_catalog):
    cases = kq_catalog["exotic-cases-by-type"].get(kq_type, [])
    if cases:
        detail_contents = my_html.anchor(
            f"{len(cases)} exotic cases", {"href": f"#{_section_id(kq_type)}"}
        )
    elif kq_type == "k1q1":
        detail_contents = "Counted only; not listed below"
    else:
        detail_contents = "0 exotic cases"
    return my_html.table_row_of_data(
        (_kq_type_label(kq_type), str(count), detail_contents)
    )


def _kq_sections(kq_catalog):
    sections = []
    for kq_type, cases in kq_catalog["exotic-cases-by-type"].items():
        sections.extend(_kq_section(kq_type, cases))
    return sections


def _kq_section(kq_type, cases):
    heading = my_html.heading_level_2(
        f"{_kq_type_label(kq_type)} ({len(cases)} cases)", {"id": _section_id(kq_type)}
    )
    return [heading, _kq_cases_table(cases)]


def _kq_cases_table(cases):
    rows = [my_html.table_row_of_headers(_KQ_FIELD_HEADERS)]
    rows.extend(_kq_case_row(case_dic) for case_dic in cases)
    return my_html.table(rows, {"class": "border-collapse limited-width"})


def _kq_case_row(case_dic):
    row_cells = []
    for field_name in _KQ_FIELD_HEADERS:
        cell_value = case_dic[field_name] or ""
        if field_name == "bcvp":
            row_cells.append(my_html.table_datum(cell_value))
            continue
        attr = {"lang": "hbo", "dir": "rtl"} if cell_value else None
        row_cells.append(my_html.table_datum(cell_value, attr))
    return my_html.table_row(tuple(row_cells))


def _kq_type_label(kq_type):
    numk = int(kq_type[1])
    numq = int(kq_type[3])
    return f"{kq_type} ({numk} ketiv, {numq} qere)"


def _section_id(kq_type):
    return f"intro-{kq_type}"


def _kq_detail_path():
    return f"{_OUT_DIR_PATH}/{_DETAIL_FILENAME_BY_KEY['kq']}"


def _json_catalogs_contents(json_output_paths):
    contents: list[object] = ["JSON catalogs: "]
    for idx, foi_key in enumerate(sorted(json_output_paths)):
        if idx:
            contents.append(" | ")
        contents.append(
            my_html.anchor(
                _json_basename(json_output_paths[foi_key]),
                {"href": _json_basename(json_output_paths[foi_key])},
            )
        )
    return tuple(contents)


def _json_link_contents(json_output_path):
    return [
        "JSON catalog: ",
        my_html.anchor(
            _json_basename(json_output_path),
            {"href": _json_basename(json_output_path)},
        ),
    ]


def _json_basename(json_output_path):
    return PurePosixPath(json_output_path).name


def _body_wrapper(contents):
    style = "max-width: 50rem; margin-left: auto; margin-right: auto"
    return [my_html.div(contents, {"style": style})]


def _write_html(title, out_path, body_contents):
    write_ctx = my_html.WriteCtx(title, out_path)
    my_html.write_html_to_file(body_contents, write_ctx, "../")
