# Initially generated by GitHub Copilot.
"""Shared mark-name abbreviation helpers for FOI pages."""


_MARK_NAME_REPLACEMENTS = (
    ("dagesh/mapiq/shuruq-dot", "dms"),
    ("meteg/siluq", "metuq"),
    ("combining-grapheme-joiner", "CGJ"),
    ("zero-width-joiner", "ZWJ"),
)


def abbreviate_mark_names(mark_names):
    abbreviated = mark_names
    for long_form, short_form in _MARK_NAME_REPLACEMENTS:
        abbreviated = abbreviated.replace(long_form, short_form)
    return abbreviated
