# Initially generated by GitHub Copilot.
"""Collect FOI data for Hebrew mark grammar exceptions and overrides."""

import unicodedata

import py_misc.my_unicode as my_unicode
import py_fois.uni_heb_char_classes as ucc
from pycmn import hebrew_letters as hl
from pycmn import hebrew_accents as ha
from pycmn import hebrew_points as hpo
from pycmn import hebrew_punctuation as hpu
from pycmn import str_defs as sd


_DUAL_CANTILLATION_LOCS = {
    ("Exodus", 20),
    ("Deuter", 5),
    ("Genesis", 35, 22),
}
_SLA_MARKS = frozenset((hpo.SHIND, hpo.SIND))
_DAGESH_MARKS = frozenset((hpo.DAGOMOSD, hpo.RAFE))
_VOWEL_MARKS = frozenset(ucc.VOWEL_POINTS)
_AOM_MARKS = frozenset(ucc.ACCENTS)
_NON_METEG_AOM_MARKS = frozenset(mark for mark in ucc.ACCENTS if mark != hpo.MTGOSLQ)
_INITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES = frozenset(
    (
        (hpo.MTGOSLQ, ha.TEL_G),
        (hpo.MTGOSLQ, ha.DEX),
        (hpo.MTGOSLQ, ha.GER_M),
        (ha.GER_M, ha.REV),
    )
)
_NONINITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES = frozenset(((hpo.MTGOSLQ, ha.OLE),))
_HATAF_VOWELS = frozenset((hpo.XSEGOL, hpo.XPATAX, hpo.XQAMATS))
_PQ_VOWELS = frozenset((hpo.PATAX, hpo.QAMATS))
_XS_VOWELS = frozenset((hpo.XIRIQ, hpo.SHEVA))
_LAMED_BELOW_AOM_MARKS = frozenset((*ha.UNI_UNDER_ACCENTS, hpo.MTGOSLQ))
_CGJ_ONLY = frozenset((sd.CGJ,))
_STRIPPED_MARKS = frozenset((hpu.UPDOT, hpu.LODOT))
_FORMAT_CONTROLS = frozenset((sd.CGJ, sd.ZWJ))
_CLASS_ORDER = (
    "ordinary",
    "explicit-order",
    "initial-double-aom",
    "multi-vowel",
    "noninitial-double-aom",
    "unexpected-mark",
    "other-ordering",
)


def init():
    return {
        "summary-counts": {
            "total-clusters": 0,
            "excluded-atoms": 0,
            "ordinary": 0,
            "allowed-overrides": 0,
            "exotic": 0,
        },
        "class-counts": {class_key: 0 for class_key in _CLASS_ORDER},
        "sequence-counts-by-class": {class_key: {} for class_key in _CLASS_ORDER},
        "cases-by-class": {class_key: [] for class_key in _CLASS_ORDER[1:]},
    }


def collect_for_verse(fois, bcv, verse):
    if _is_excluded(*bcv):
        fois["summary-counts"]["excluded-atoms"] += len(verse)
        return
    for atidx, atom in enumerate(verse, start=1):
        assert isinstance(atom, list)
        assert len(atom) == 2
        atom_type, atom_text = atom
        bcvp = *bcv, atidx
        for cluster_idx, cluster in enumerate(_split_clusters(atom_text), start=1):
            _collect_for_cluster(fois, bcvp, atom_type, atom_text, cluster_idx, cluster)


def _is_excluded(bkid, chnu, vrnu):
    return (bkid, chnu) in _DUAL_CANTILLATION_LOCS or (
        bkid,
        chnu,
        vrnu,
    ) in _DUAL_CANTILLATION_LOCS


def _collect_for_cluster(fois, bcvp, atom_type, atom_text, cluster_idx, cluster):
    summary_counts = fois["summary-counts"]
    summary_counts["total-clusters"] += 1
    cluster_class, status_key = _classify(cluster, cluster_idx)
    summary_counts[status_key] += 1
    fois["class-counts"][cluster_class] += 1
    sequence = _mark_sequence(cluster)
    seq_counts = fois["sequence-counts-by-class"][cluster_class]
    seq_counts[sequence] = seq_counts.get(sequence, 0) + 1
    if cluster_class == "ordinary":
        return
    fois["cases-by-class"][cluster_class].append(
        {
            "bcvp": _bcvp_str(bcvp),
            "atom-type": atom_type,
            "atom": atom_text,
            "cluster-index": cluster_idx,
            "cluster": cluster["letter"] + "".join(cluster["marks"]),
            "sequence": sequence,
            "mark-names": ", ".join(my_unicode.name(mark) for mark in cluster["marks"]),
        }
    )


def _split_clusters(atom_text):
    clusters = []
    current = None
    for ch in atom_text:
        if ch in ucc.LETTERS:
            current = {"letter": ch, "marks": []}
            clusters.append(current)
            continue
        if current is None:
            continue
        if unicodedata.category(ch) in ("Mn", "Cf"):
            if ch in _STRIPPED_MARKS:
                continue
            current["marks"].append(ch)
    return clusters


def _classify(cluster, cluster_idx):
    marks = cluster["marks"]
    if _unexpected_marks(marks):
        return "unexpected-mark", "exotic"
    if _is_ordinary(cluster, cluster_idx):
        return "ordinary", "ordinary"
    if any(mark in _FORMAT_CONTROLS for mark in marks):
        return "explicit-order", "allowed-overrides"
    if cluster_idx == 1 and _is_initial_double_aom(marks):
        return "initial-double-aom", "allowed-overrides"
    if _mark_sequence(marks).count("v") > 1:
        return "multi-vowel", "exotic"
    if _mark_sequence(marks).count("a") > 1:
        return "noninitial-double-aom", "exotic"
    return "other-ordering", "exotic"


def _is_ordinary(cluster, cluster_idx):
    marks = cluster["marks"]
    if _is_expected_hataf_zwj_meteg(marks):
        return True
    if _is_expected_meteg_cgj_vowel(marks):
        return True
    if _is_expected_lamed_pq_maybe_accent_cgj_xs(cluster["letter"], marks):
        return True
    if any(mark in _FORMAT_CONTROLS for mark in marks):
        return False
    marks_without_format_controls = _marks_without_format_controls(marks)
    if _is_expected_ordinary_double_aom_suffix(
        marks_without_format_controls, cluster_idx
    ):
        return True
    sequence = _mark_sequence(marks_without_format_controls)
    if not _is_in_nondecreasing_order(sequence):
        return False
    return all(sequence.count(mark_class) <= 1 for mark_class in "sdva")


def _marks_without_format_controls(marks):
    return [mark for mark in marks if mark not in _FORMAT_CONTROLS]


def _is_expected_hataf_zwj_meteg(marks):
    idx = 0
    if idx < len(marks) and marks[idx] in _SLA_MARKS:
        idx += 1
    if idx < len(marks) and marks[idx] in _DAGESH_MARKS:
        idx += 1
    if idx + 2 >= len(marks):
        return False
    if marks[idx] not in _HATAF_VOWELS:
        return False
    if marks[idx + 1] != sd.ZWJ or marks[idx + 2] != hpo.MTGOSLQ:
        return False
    trailing_marks = marks[idx + 3 :]
    return len(trailing_marks) <= 1 and all(
        mark in _NON_METEG_AOM_MARKS for mark in trailing_marks
    )


def _is_expected_meteg_cgj_vowel(marks):
    idx = 0
    if idx < len(marks) and marks[idx] in _SLA_MARKS:
        idx += 1
    if idx < len(marks) and marks[idx] in _DAGESH_MARKS:
        idx += 1
    if idx + 2 >= len(marks):
        return False
    if marks[idx] != hpo.MTGOSLQ:
        return False
    if marks[idx + 1] not in _CGJ_ONLY or marks[idx + 2] not in _VOWEL_MARKS:
        return False
    trailing_marks = marks[idx + 3 :]
    return len(trailing_marks) <= 1 and all(
        mark in _NON_METEG_AOM_MARKS for mark in trailing_marks
    )


def _is_expected_lamed_pq_maybe_accent_cgj_xs(letter, marks):
    if letter != hl.LAMED:
        return False
    if len(marks) == 2:
        return marks[0] in _PQ_VOWELS and marks[1] in _XS_VOWELS
    if len(marks) == 3:
        if marks[0] in _PQ_VOWELS and marks[1] in _CGJ_ONLY and marks[2] in _XS_VOWELS:
            return True
        return (
            marks[0] in _PQ_VOWELS
            and marks[1] in _XS_VOWELS
            and marks[2] in ha.UNI_OVER_ACCENTS
        )
    if len(marks) == 4:
        return (
            marks[0] in _PQ_VOWELS
            and marks[1] in _LAMED_BELOW_AOM_MARKS
            and marks[2] in _CGJ_ONLY
            and marks[3] in _XS_VOWELS
        )
    return False


def _is_expected_ordinary_double_aom_suffix(marks, cluster_idx):
    if len(marks) < 2:
        return False
    suffix = tuple(marks[-2:])
    if suffix in _INITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES:
        if cluster_idx != 1:
            return False
    elif suffix not in _NONINITIAL_ORDINARY_DOUBLE_AOM_SUFFIXES:
        return False
    prefix = marks[:-2]
    sequence = _mark_sequence(prefix)
    return _is_in_nondecreasing_order(sequence) and all(
        sequence.count(mark_class) <= 1 for mark_class in "sdv"
    )


def _is_initial_double_aom(marks):
    sequence = _mark_sequence(marks)
    if not sequence.endswith("aa"):
        return False
    prefix = sequence[:-2]
    return _is_in_nondecreasing_order(prefix) and all(
        prefix.count(mark_class) <= 1 for mark_class in "sdv"
    )


def _is_in_nondecreasing_order(sequence):
    sort_order = {"s": 0, "d": 1, "v": 2, "a": 3}
    last = -1
    for mark_class in sequence:
        current = sort_order[mark_class]
        if current < last:
            return False
        last = current
    return True


def _unexpected_marks(marks):
    return [mark for mark in marks if _mark_class(mark) == "?"]


def _mark_sequence(cluster_or_marks):
    marks = (
        cluster_or_marks["marks"]
        if isinstance(cluster_or_marks, dict)
        else cluster_or_marks
    )
    return "".join(_mark_class(mark) for mark in marks if _mark_class(mark) != "f")


def _mark_class(mark):
    if mark in _SLA_MARKS:
        return "s"
    if mark in _DAGESH_MARKS:
        return "d"
    if mark in _VOWEL_MARKS:
        return "v"
    if mark in _AOM_MARKS:
        return "a"
    if mark in _FORMAT_CONTROLS:
        return "f"
    return "?"


def _bcvp_str(bcvp):
    bkid, chnu, vrnu, atnu = bcvp
    return f"{bkid} {chnu}:{vrnu}.{atnu}"
