# Initially generated by GitHub Copilot.
"""Collect FOI data for mark grammar 2."""

import py_misc.my_unicode as my_unicode
import py_fois.fois_mark_grammar_foi as fois_mark_grammar_foi
from pycmn import hebrew_points as hpo


_TITLE = "mark grammar 2"
_MAX_EXAMPLES_PER_BUCKET = 5
_ADDITIONAL_PATTERNS_INTRO = (
    "Patterns treated as ordinary (after an optional shsi-dot and an optional "
    "dms-r):"
)
_ADDITIONAL_PATTERN_DISPLAY_ITEMS = (
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "meteg, CGJ, vowel, optional pre-wm."
    ),
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "On lamed only:",
        (
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "pq-vowel, ba-is, CGJ, xs-vowel."
            ),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "pq-vowel, xs-vowel, optional above-accent."
            ),
        ),
    ),
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "xataf, ZWJ, meteg, optional pre-wm."
    ),
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "On the first letter of a word only (after an optional vowel):",
        (
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem("munaḥ, deḥi."),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem("meteg, pre-wm."),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
                "geresh or gershayim, telisha gedolah."
            ),
            fois_mark_grammar_foi.OrdinaryPatternDisplayItem("geresh muqdam, revia."),
        ),
    ),
    fois_mark_grammar_foi.OrdinaryPatternDisplayItem(
        "On any letter (after an optional vowel): meteg, oleh."
    ),
)
_ABBREVIATION_ROWS = (
    ("shsi-dot", "shin-dot or sin-dot"),
    ("dms-r", "dms (see below) or rafeh"),
    ("dms", "dagesh/mapiq/shuruq-dot"),
    ("ba-is", "below-accent (including silluq)"),
    ("CGJ", "combining grapheme joiner"),
    ("ZWJ", "zero-width joiner"),
    ("xataf", "one of the three ḥataf vowels"),
    ("pq-vowel", "pataḥ or qamats"),
    ("xs-vowel", "ḥiriq or sheva"),
    (
        "pre-wm",
        "prepositive that can occur with meteg: telisha gedolah, deḥi, geresh muqdam",
    ),
)
_RARE_BUCKET_SPEC = {
    "key": "rare-default-rafeh-sdva",
    "label": "Totally ordinary: optional shsi-dot, rafeh, vowel, aom.",
}
_LEAF_BUCKET_SPECS = (
    {
        "key": "meteg-cgj-vowel",
        "label": "meteg, CGJ, vowel, optional pre-wm.",
        "forks": (
            ("without-pre-wm", "without pre-wm"),
            ("with-pre-wm", "with pre-wm"),
        ),
    },
    {
        "key": "lamed-pq-cgj-xs",
        "label": "On lamed only: pq-vowel, ba-is, CGJ, xs-vowel.",
    },
    {
        "key": "lamed-pq-xs-above-aom",
        "label": "On lamed only: pq-vowel, xs-vowel, optional above-accent.",
        "forks": (
            ("without-above-accent", "without above-accent"),
            ("with-above-accent", "with above-accent"),
        ),
    },
    {
        "key": "hataf-zwj-meteg",
        "label": "xataf, ZWJ, meteg, optional pre-wm.",
        "forks": (
            ("without-pre-wm", "without pre-wm"),
            ("with-pre-wm", "with pre-wm"),
        ),
    },
    {
        "key": "initial-munah-dehi",
        "label": "On the first letter of a word only (after an optional vowel): munaḥ, deḥi.",
    },
    {
        "key": "initial-meteg-pre-wm",
        "label": "On the first letter of a word only (after an optional vowel): meteg, pre-wm.",
    },
    {
        "key": "initial-geresh-telisha-gedolah",
        "label": "On the first letter of a word only (after an optional vowel): geresh or gershayim, telisha gedolah.",
    },
    {
        "key": "initial-geresh-muqdam-revia",
        "label": "On the first letter of a word only (after an optional vowel): geresh muqdam, revia.",
    },
    {
        "key": "noninitial-meteg-oleh",
        "label": "On any letter (after an optional vowel): meteg, oleh.",
    },
)


def title():
    return _TITLE


def additional_patterns_intro():
    return _ADDITIONAL_PATTERNS_INTRO


def additional_pattern_display_items():
    return _ADDITIONAL_PATTERN_DISPLAY_ITEMS


def abbreviation_rows():
    return _ABBREVIATION_ROWS


def rare_bucket_spec():
    return _RARE_BUCKET_SPEC


def leaf_bucket_specs():
    return _LEAF_BUCKET_SPECS


def init():
    return {
        "summary-counts": {
            "tracked-clusters": 0,
            "rare-default-rafeh-sdva": 0,
        },
        "rare-bucket": _init_bucket(_RARE_BUCKET_SPEC),
        "leaf-buckets": {
            spec["key"]: _init_bucket(spec) for spec in _LEAF_BUCKET_SPECS
        },
    }


def collect_for_verse(fois, bcv, verse):
    if fois_mark_grammar_foi.is_excluded(*bcv):
        return
    for atidx, atom in enumerate(verse, start=1):
        assert isinstance(atom, list)
        assert len(atom) >= 2
        atom_text = atom[1]
        atom_note_data = _atom_note_data(atom)
        bcvp = *bcv, atidx
        for cluster_idx, cluster in enumerate(
            fois_mark_grammar_foi.split_atom_clusters(atom_text, strip_marks=True),
            start=1,
        ):
            ordinary_match = fois_mark_grammar_foi.ordinary_pattern_match(
                cluster, cluster_idx
            )
            if ordinary_match is None:
                continue
            case_dic = _case_dic(bcvp, atom_text, atom_note_data, cluster_idx, cluster)
            if _is_rare_default_rafeh_sdva(cluster, ordinary_match):
                _record_case(fois["rare-bucket"], case_dic)
                fois["summary-counts"]["tracked-clusters"] += 1
                fois["summary-counts"]["rare-default-rafeh-sdva"] += 1
                continue
            if ordinary_match.leaf_key is None:
                continue
            bucket = fois["leaf-buckets"][ordinary_match.leaf_key]
            _record_case(bucket, case_dic)
            fois["summary-counts"]["tracked-clusters"] += 1
            if ordinary_match.fork_key is None or "fork-buckets" not in bucket:
                continue
            _record_case(bucket["fork-buckets"][ordinary_match.fork_key], case_dic)


def _init_bucket(spec):
    bucket = {
        "key": spec["key"],
        "label": spec["label"],
        "count": 0,
        "examples": [],
    }
    if "forks" not in spec:
        return bucket
    bucket["fork-buckets"] = {
        fork_key: {
            "key": fork_key,
            "label": fork_label,
            "count": 0,
            "examples": [],
        }
        for fork_key, fork_label in spec["forks"]
    }
    return bucket


def _record_case(bucket, case_dic):
    bucket["count"] += 1
    if len(bucket["examples"]) >= _MAX_EXAMPLES_PER_BUCKET:
        return
    bucket["examples"].append(case_dic)


def _is_rare_default_rafeh_sdva(cluster, ordinary_match):
    return (
        ordinary_match.is_default_ordinary
        and hpo.RAFE in cluster["marks"]
        and (fois_mark_grammar_foi.mark_sequence(cluster) in ("dva", "sdva"))
    )


def _case_dic(bcvp, atom_text, atom_note_data, cluster_idx, cluster):
    return {
        "bcvp": _bcvp_str(bcvp),
        "notes": _notes_str(atom_note_data),
        "atom": atom_text,
        "cluster-index": cluster_idx,
        "sequence": fois_mark_grammar_foi.mark_sequence(cluster),
        "mark names": ", ".join(my_unicode.name(mark) for mark in cluster["marks"]),
    }


def _atom_note_data(atom):
    if len(atom) < 3:
        return None
    note_data = atom[2]
    if not note_data["types"]:
        return None
    return note_data


def _notes_str(atom_note_data):
    if atom_note_data is None:
        return ""
    return ",".join(atom_note_data["types"])


def _bcvp_str(bcvp):
    bkid, chnu, vrnu, atnu = bcvp
    return f"{bkid} {chnu}:{vrnu}.{atnu}"
